export const beginnerVocabulary = [
  { en: 'A', ne: 'एक' },
  { en: 'Ability', ne: 'क्षमता' },
  { en: 'Able', ne: 'सक्षम' },
  { en: 'About', ne: 'बारेमा' },
  { en: 'Above', ne: 'माथि' },
  { en: 'Accept', ne: 'स्वीकार गर्नु' },
  { en: 'Accident', ne: 'दुर्घटना' },
  { en: 'Activity', ne: 'गतिविधि' },
  { en: 'Actor', ne: 'अभिनेता' },
  { en: 'Add', ne: 'जोड्नु' },
  { en: 'Afraid', ne: 'डराएको' },
  { en: 'After', ne: 'पछि' },
  { en: 'Afternoon', ne: 'दिउँसो' },
  { en: 'Again', ne: 'फेरि' },
  { en: 'Age', ne: 'उमेर' },
  { en: 'Air', ne: 'हावा' },
  { en: 'Airport', ne: 'विमानस्थल' },
  { en: 'All', ne: 'सबै' },
  { en: 'Alone', ne: 'एक्लै' },
  { en: 'Always', ne: 'सधैं' },
  { en: 'Angry', ne: 'रिसाएको' },
  { en: 'Animal', ne: 'जनावर' },
  { en: 'Answer', ne: 'उत्तर' },
  { en: 'Apple', ne: 'स्याउ' },
  { en: 'Area', ne: 'क्षेत्र' },
  { en: 'Arm', ne: 'हात' },
  { en: 'Around', ne: 'वरिपरि' },
  { en: 'August', ne: 'अगस्ट' },
  { en: 'Aunt', ne: 'फुपू/मौसी' },
  { en: 'Autumn', ne: 'शरद ऋतु' },
  { en: 'Away', ne: 'टाढा' },
  { en: 'Baby', ne: 'बच्चा' },
  { en: 'Back', ne: 'पछाडि' },
  { en: 'Bad', ne: 'खराब' },
  { en: 'Bag', ne: 'झोला' },
  { en: 'Ball', ne: 'बल' },
  { en: 'Bank', ne: 'बैंक' },
  { en: 'Beautiful', ne: 'सुन्दर' },
  { en: 'Because', ne: 'किनभने' },
  { en: 'Bed', ne: 'ओछ्यान' },
  { en: 'Before', ne: 'अघि' },
  { en: 'Behind', ne: 'पछाडि' },
  { en: 'Best', ne: 'सबैभन्दा राम्रो' },
  { en: 'Better', ne: 'राम्रो' },
  { en: 'Big', ne: 'ठूलो' },
  { en: 'Bird', ne: 'चरा' },
  { en: 'Birthday', ne: 'जन्मदिन' },
  { en: 'Black', ne: 'कालो' },
  { en: 'Book', ne: 'किताब' },
  { en: 'Boy', ne: 'केटा' },
  { en: 'Bread', ne: 'रोटी' },
  { en: 'Brother', ne: 'दाजु/भाइ' },
  { en: 'Bus', ne: 'बस' },
  { en: 'Busy', ne: 'व्यस्त' },
  { en: 'Camera', ne: 'क्यामेरा' },
  { en: 'Can', ne: 'सक्नु' },
  { en: 'Car', ne: 'कार' },
  { en: 'Cat', ne: 'बिरालो' },
  { en: 'Center', ne: 'केन्द्र' },
  { en: 'Chair', ne: 'कुर्सी' },
  { en: 'Child', ne: 'बच्चा' },
  { en: 'City', ne: 'सहर' },
  { en: 'Cold', ne: 'चिसो' },
  { en: 'Cool', ne: 'चिसो/शान्त' },
  { en: 'Country', ne: 'देश' },
  { en: 'Daily', ne: 'दैनिक' },
  { en: 'Dance', ne: 'नाच्नु' },
  { en: 'Dark', ne: 'अँध्यारो' },
  { en: 'Day', ne: 'दिन' },
  { en: 'Dear', ne: 'प्रिय' },
  { en: 'Death', ne: 'मृत्यु' },
  { en: 'Deep', ne: 'गहिरो' },
  { en: 'Delete', ne: 'मेट्नु' },
  { en: 'Dog', ne: 'कुकुर' },
  { en: 'Door', ne: 'ढोका' },
  { en: 'Down', ne: 'तल' },
  { en: 'Drink', ne: 'पिउनु' },
  { en: 'Dry', ne: 'सुक्खा' },
  { en: 'During', ne: 'समयमा' },
  { en: 'Dust', ne: 'धुलो' },
  { en: 'Each', ne: 'प्रत्येक' },
  { en: 'Early', ne: 'चाँडै' },
  { en: 'Earth', ne: 'पृथ्वी' },
  { en: 'East', ne: 'पूर्व' },
  { en: 'Easy', ne: 'सजिलो' },
  { en: 'Edge', ne: 'किनारा' },
  { en: 'Effect', ne: 'प्रभाव' },
  { en: 'Egg', ne: 'अण्डा' },
  { en: 'Eight', ne: 'आठ' },
  { en: 'Electric', ne: 'बिजुली' },
  { en: 'Elephant', ne: 'हात्ती' },
  { en: 'Engine', ne: 'इन्जिन' },
  { en: 'English', ne: 'अंग्रेजी' },
  { en: 'Enough', ne: 'पर्याप्त' },
  { en: 'Equal', ne: 'बराबर' },
  { en: 'Evening', ne: 'साँझ' },
  { en: 'Event', ne: 'घटना' },
  { en: 'Ever', ne: 'कहिल्यै' },
  { en: 'Every', ne: 'प्रत्येक' },
  { en: 'Exit', ne: 'निस्कनु' },
  { en: 'Eye', ne: 'आँखा' },
  { en: 'Fact', ne: 'तथ्य' },
  { en: 'Factory', ne: 'कारखाना' },
  { en: 'Fair', ne: 'निष्पक्ष' },
  { en: 'Family', ne: 'परिवार' },
  { en: 'Famous', ne: 'प्रसिद्ध' },
  { en: 'Far', ne: 'टाढा' },
  { en: 'Farm', ne: 'खेत' },
  { en: 'Fast', ne: 'छिटो' },
  { en: 'Fat', ne: 'मोटो' },
  { en: 'Father', ne: 'बुबा' },
  { en: 'Fear', ne: 'डर' },
  { en: 'Female', ne: 'महिला' },
  { en: 'Fence', ne: 'बार' },
  { en: 'Festival', ne: 'चाड' },
  { en: 'Few', ne: 'केही' },
  { en: 'File', ne: 'फाइल' },
  { en: 'Film', ne: 'चलचित्र' },
  { en: 'Final', ne: 'अन्तिम' },
  { en: 'Fine', ne: 'राम्रो' },
  { en: 'Finger', ne: 'औंला' },
  { en: 'Fire', ne: 'आगो' },
  { en: 'First', ne: 'पहिलो' },
  { en: 'Fish', ne: 'माछा' },
  { en: 'Five', ne: 'पाँच' },
  { en: 'Flag', ne: 'झण्डा' },
  { en: 'Floor', ne: 'भुइँ' },
  { en: 'Flower', ne: 'फूल' },
  { en: 'Fly', ne: 'उड्नु' },
  { en: 'Food', ne: 'खाना' },
  { en: 'Foot', ne: 'खुट्टा' },
  { en: 'Forest', ne: 'जंगल' },
  { en: 'Forward', ne: 'अगाडि' },
  { en: 'Friend', ne: 'साथी' },
  { en: 'Front', ne: 'अगाडि' },
  { en: 'Game', ne: 'खेल' },
  { en: 'Garden', ne: 'बगैँचा' },
  { en: 'Gift', ne: 'उपहार' },
  { en: 'Girl', ne: 'केटी' },
  { en: 'Glass', ne: 'गिलास' },
  { en: 'God', ne: 'भगवान' },
  { en: 'Good', ne: 'राम्रो' },
  { en: 'Green', ne: 'हरियो' },
  { en: 'Group', ne: 'समूह' },
  { en: 'Happy', ne: 'खुशी' },
  { en: 'Hard', ne: 'कठिन' },
  { en: 'Head', ne: 'टाउको' },
  { en: 'High', ne: 'उच्च' },
  { en: 'Home', ne: 'घर' },
  { en: 'House', ne: 'घर' },
  { en: 'Hungry', ne: 'भोकाएको' },
  { en: 'Important', ne: 'महत्वपूर्ण' },
  { en: 'In', ne: 'भित्र' },
  { en: 'Internet', ne: 'इन्टरनेट' },
  { en: 'Job', ne: 'काम' },
  { en: 'Journey', ne: 'यात्रा' },
  { en: 'Joy', ne: 'खुशी' },
  { en: 'Key', ne: 'चाबी' },
  { en: 'Kind', ne: 'दयालु' },
  { en: 'King', ne: 'राजा' },
  { en: 'Large', ne: 'ठूलो' },
  { en: 'Laugh', ne: 'हाँस्नु' },
  { en: 'Work', ne: 'काम' },
  { en: 'Write', ne: 'लेख्नु' },
  { en: 'Water', ne: 'पानी' },
  { en: 'Weather', ne: 'मौसम' },
  { en: 'Week', ne: 'हप्ता' },
  { en: 'Win', ne: 'जित्नु' },
  { en: 'Woman', ne: 'महिला' },
  { en: 'World', ne: 'संसार' },
  { en: 'Year', ne: 'वर्ष' },
  { en: 'Yes', ne: 'हो' },
  { en: 'Zero', ne: 'शून्य' },
  { en: 'Left', ne: 'बाँया' },
  { en: 'Leg', ne: 'खुट्टा' },
  { en: 'Letter', ne: 'चिठ्ठी' },
  { en: 'Life', ne: 'जीवन' },
  { en: 'Line', ne: 'रेखा' },
  { en: 'List', ne: 'सूची' },
  { en: 'Little', ne: 'सानो' },
  { en: 'Local', ne: 'स्थानीय' },
  { en: 'Long', ne: 'लामो' },
  { en: 'Love', ne: 'माया' },
  { en: 'Low', ne: 'कम' },
  { en: 'Luck', ne: 'भाग्य' },
  { en: 'Lunch', ne: ' खाजा' },
  { en: 'Machine', ne: 'मेसिन' },
  { en: 'Main', ne: 'मुख्य' },
  { en: 'Man', ne: 'पुरुष' },
  { en: 'Many', ne: 'धेरै' },
  { en: 'Map', ne: 'नक्सा' },
  { en: 'Market', ne: 'बजार' },
  { en: 'Marriage', ne: 'विवाह' },
  { en: 'Matter', ne: 'कुरा' },
  { en: 'May', ne: 'सक्छ' },
  { en: 'Mean', ne: 'अर्थ' },
  { en: 'Member', ne: 'सदस्य' },
  { en: 'Metal', ne: 'धातु' },
  { en: 'Middle', ne: 'बीच' },
  { en: 'Milk', ne: 'दूध' },
  { en: 'Minute', ne: 'मिनेट' },
  { en: 'Mistake', ne: 'गल्ती' },
  { en: 'Money', ne: 'पैसा' },
  { en: 'Month', ne: 'महिना' },
  { en: 'Moon', ne: 'चन्द्रमा' },
  { en: 'Morning', ne: 'बिहान' },
  { en: 'Mother', ne: 'आमा' },
  { en: 'Mountain', ne: 'पहाड' },
  { en: 'Music', ne: 'संगीत' },
  { en: 'Must', ne: 'पर्छ' },
  { en: 'Natural', ne: 'प्राकृतिक' },
  { en: 'Near', ne: 'नजिक' },
  { en: 'Never', ne: 'कहिल्यै होइन' },
  { en: 'New', ne: 'नयाँ' },
  { en: 'News', ne: 'समाचार' },
  { en: 'Night', ne: 'रात' },
  { en: 'No', ne: 'होइन' },
  { en: 'Noise', ne: 'आवाज' },
  { en: 'Normal', ne: 'सामान्य' },
  { en: 'North', ne: 'उत्तर' },
  { en: 'Nose', ne: 'नाक' },
  { en: 'Note', ne: 'टिपोट' },
  { en: 'Nothing', ne: 'केही पनि होइन' },
  { en: 'Now', ne: 'अहिले' },
  { en: 'Number', ne: 'संख्या' },
  { en: 'Nurse', ne: 'नर्स' },
  { en: 'Office', ne: 'कार्यालय' },
  { en: 'Often', ne: 'प्राय' },
  { en: 'Oil', ne: 'तेल' },
  { en: 'Old', ne: 'पुरानो' },
  { en: 'Orange', ne: 'सुन्तला' },
  { en: 'Other', ne: 'अन्य' },
  { en: 'Outside', ne: 'बाहिर' },
  { en: 'Page', ne: 'पाना' },
  { en: 'Pain', ne: 'पीडा' },
  { en: 'Paper', ne: 'कागज' },
  { en: 'Parent', ne: 'अभिभावक' },
  { en: 'Park', ne: 'पार्क' },
  { en: 'Part', ne: 'भाग' },
  { en: 'Party', ne: 'पार्टी' },
  { en: 'Past', ne: 'बितेको' },
  { en: 'Peace', ne: 'शान्ति' },
  { en: 'People', ne: 'मानिसहरू' },
  { en: 'Person', ne: 'व्यक्ति' },
  { en: 'Phone', ne: 'फोन' },
  { en: 'Photo', ne: 'फोटो' },
  { en: 'Picture', ne: 'चित्र' },
  { en: 'Piece', ne: 'टुक्रा' },
  { en: 'Place', ne: 'ठाउँ' },
  { en: 'Plant', ne: 'बिरुवा' },
  { en: 'Please', ne: 'कृपया' },
  { en: 'Police', ne: 'प्रहरी' },
  { en: 'Poor', ne: 'गरिब' },
  { en: 'Popular', ne: 'लोकप्रिय' },
  { en: 'Possible', ne: 'सम्भव' },
  { en: 'Power', ne: 'शक्ति' },
  { en: 'Price', ne: 'मूल्य' },
  { en: 'Problem', ne: ' समस्या' },
  { en: 'Promise', ne: 'वाचा' },
  { en: 'Public', ne: 'सार्वजनिक' },
  { en: 'Quick', ne: 'छिटो' },
  { en: 'Quiet', ne: 'शान्त' },
  { en: 'Race', ne: 'दौड' },
  { en: 'Radio', ne: 'रेडियो' },
  { en: 'Rain', ne: 'पानी' },
  { en: 'Ready', ne: 'तयार' },
  { en: 'Real', ne: 'वास्तविक' },
  { en: 'Red', ne: 'रातो' },
  { en: 'Relation', ne: 'सम्बन्ध' },
  { en: 'Repeat', ne: 'दोहोर्याउनु' },
  { en: 'Rest', ne: 'आराम' },
  { en: 'Rich', ne: 'धनी' },
  { en: 'Right', ne: 'दायाँ/सही' },
  { en: 'River', ne: 'नदी' },
  { en: 'Road', ne: 'बाटो' },
  { en: 'Rock', ne: 'ढुंगा' },
  { en: 'Room', ne: 'कोठा' },
  { en: 'Rule', ne: 'नियम' },
  { en: 'Sad', ne: 'दुःखी' },
  { en: 'Safe', ne: 'सुरक्षित' },
  { en: 'Salt', ne: 'नुन' },
  { en: 'Same', ne: 'उस्तै' },
  { en: 'School', ne: 'विद्यालय' },
  { en: 'Sea', ne: 'समुद्र' },
  { en: 'Search', ne: 'खोज्नु' },
  { en: 'Seat', ne: 'सिट' },
  { en: 'Second', ne: 'दोस्रो' },
  { en: 'Sense', ne: 'ज्ञान/इन्द्रिय' },
  { en: 'Serious', ne: 'गम्भीर' },
  { en: 'Seven', ne: 'सात' },
  { en: 'Several', ne: 'धेरै' },
  { en: 'Shape', ne: 'आकार' },
  { en: 'Sharp', ne: 'धारिलो' },
  { en: 'She', ne: 'उनी (महिला)' },
  { en: 'Ship', ne: 'जहाज' },
  { en: 'Short', ne: 'छोटो' },
  { en: 'Sick', ne: 'बिरामी' },
  { en: 'Side', ne: 'पक्ष' },
  { en: 'Sign', ne: 'संकेत' },
  { en: 'Simple', ne: 'सरल' },
  { en: 'Since', ne: 'देखि' },
  { en: 'Single', ne: 'एकल' },
  { en: 'Sister', ne: 'दिदी/बहिनी' },
  { en: 'Size', ne: 'आकार' },
  { en: 'Slow', ne: 'ढिलो' },
  { en: 'Small', ne: 'सानो' },
  { en: 'Smoke', ne: 'धुवाँ' },
  { en: 'Snow', ne: 'हिउँ' },
  { en: 'Social', ne: 'सामाजिक' },
  { en: 'Soft', ne: 'नरम' },
  { en: 'Soil', ne: ' माटो' },
  { en: 'Some', ne: 'केही' },
  { en: 'Son', ne: 'छोरा' },
  { en: 'Song', ne: 'गीत' },
  { en: 'Soon', ne: 'चाँडै' },
  { en: 'Sorry', ne: 'माफ गर्नुहोस्' },
  { en: 'Soup', ne: 'सुप' },
  { en: 'South', ne: 'दक्षिण' },
  { en: 'Space', ne: 'अन्तरिक्ष' },
  { en: 'Special', ne: 'विशेष' },
  { en: 'Speed', ne: 'गति' },
  { en: 'Spell', ne: 'हिज्जे' },
  { en: 'Sport', ne: 'खेलकुद' },
  { en: 'Spring', ne: 'वसन्त' },
  { en: 'Star', ne: 'तारा' },
  { en: 'State', ne: 'राज्य' },
  { en: 'Step', ne: 'पाइला' },
  { en: 'Still', ne: 'अझै' },
  { en: 'Stock', ne: 'भण्डार' },
  { en: 'Story', ne: 'कथा' },
  { en: 'Street', ne: 'सडक' },
  { en: 'Strong', ne: 'बलियो' },
  { en: 'Style', ne: 'शैली' },
  { en: 'Subject', ne: 'विषय' },
  { en: 'Such', ne: 'यस्तो' },
  { en: 'Sugar', ne: 'चिनी' },
  { en: 'Summer', ne: 'गर्मी' },
  { en: 'Sun', ne: 'सूर्य' },
  { en: 'Sunday', ne: 'आइतबार' },
  { en: 'Sure', ne: 'निश्चित' },
  { en: 'Sweet', ne: 'मीठो' },
  { en: 'Swim', ne: 'पौडिनु' },
  { en: 'Table', ne: 'टेबल' },
  { en: 'Tall', ne: ' अग्लो' },
  { en: 'Taste', ne: 'स्वाद' },
  { en: 'Tax', ne: 'कर' },
  { en: 'Team', ne: 'टोली' },
  { en: 'Telephone', ne: 'टेलिफोन' },
  { en: 'Television', ne: 'टेलिभिजन' },
  { en: 'Temperature', ne: 'तापक्रम' },
  { en: 'Text', ne: 'पाठ' },
  { en: 'Than', ne: 'भन्दा' },
  { en: 'That', ne: 'त्यो' },
  { en: 'The', ne: '(निर्दिष्ट शब्द)' },
  { en: 'Their', ne: 'उनीहरूको' },
  { en: 'Them', ne: 'उनीहरूलाई' },
  { en: 'Then', ne: 'त्यसपछि' },
  { en: 'There', ne: 'त्यहाँ' },
  { en: 'These', ne: 'यी' },
  { en: 'They', ne: 'उनीहरू' },
  { en: 'Thing', ne: 'कुरा' },
  { en: 'Third', ne: 'तेस्रो' },
  { en: 'This', ne: 'यो' },
  { en: 'Those', ne: 'ती' },
  { en: 'Though', ne: 'यद्यपि' },
  { en: 'Thought', ne: 'विचार' },
  { en: 'Thousand', ne: 'हजार' },
  { en: 'Three', ne: 'तीन' },
  { en: 'Through', ne: 'मार्फत' },
  { en: 'Time', ne: 'समय' },
  { en: 'Today', ne: 'आज' },
  { en: 'Together', ne: 'सँगै' },
  { en: 'Tomorrow', ne: 'भोलि' },
  { en: 'Tree', ne: 'रूख' },
  { en: 'Trouble', ne: 'समस्या' },
  { en: 'True', ne: 'सत्य' },
  { en: 'TV', ne: 'टिभी' },
  { en: 'Two', ne: 'दुई' },
  { en: 'Type', ne: 'प्रकार' },
  { en: 'Understand', ne: 'बुझ्नु' },
  { en: 'University', ne: 'विश्वविद्यालय' },
  { en: 'Until', ne: 'सम्म' },
  { en: 'Up', ne: 'माथि' },
  { en: 'Use', ne: 'प्रयोग गर्नु' },
  { en: 'Useful', ne: 'उपयोगी' },
  { en: 'Usual', ne: 'सामान्य' },
  { en: 'Vacation', ne: 'छुट्टी' },
  { en: 'Very', ne: 'धेरै' },
  { en: 'Village', ne: 'गाउँ' },
  { en: 'Visit', ne: 'भ्रमण गर्नु' },
  { en: 'Voice', ne: 'आवाज' },
  { en: 'Wait', ne: 'कुर्नु' },
  { en: 'Wake', ne: 'उठ्नु' },
  { en: 'Walk', ne: 'हिँड्नु' },
  { en: 'Want', ne: 'चाहनु' },
  { en: 'War', ne: 'युद्ध' },
  { en: 'Warm', ne: 'न्यानो' },
  { en: 'Wash', ne: 'धुनु' },
  { en: 'Watch', ne: 'हेर्नु' },
  { en: 'Way', ne: 'बाटो' },
  { en: 'Weak', ne: 'कमजोर' },
  { en: 'Weight', ne: 'तौल' },
  { en: 'Welcome', ne: 'स्वागत' },
  { en: 'Well', ne: 'राम्रो' },
  { en: 'West', ne: 'पश्चिम' },
  { en: 'Wet', ne: 'भिजेको' },
  { en: 'What', ne: 'के' },
  { en: 'When', ne: 'कहिले' },
  { en: 'Where', ne: 'कहाँ' },
  { en: 'Which', ne: 'कुन' },
  { en: 'While', ne: 'जबकि' },
  { en: 'White', ne: 'सेतो' },
  { en: 'Who', ne: 'को' },
  { en: 'Whole', ne: 'सम्पूर्ण' },
  { en: 'Why', ne: 'किन' },
  { en: 'Wide', ne: 'फराकिलो' },
  { en: 'Wife', ne: 'श्रीमती' },
  { en: 'Wind', ne: 'हावा' },
  { en: 'Window', ne: 'झ्याल' },
  { en: 'Wine', ne: 'वाइन' },
  { en: 'Winter', ne: 'जाडो' },
  { en: 'Wise', ne: 'बुद्धिमान' },
  { en: 'Wish', ne: 'इच्छा' },
  { en: 'With', ne: 'सँग' },
  { en: 'Wonder', ne: 'अचम्म मान्नु' },
  { en: 'Word', ne: 'शब्द' },
  { en: 'Worry', ne: 'चिन्ता गर्नु' },
  { en: 'Wrong', ne: 'गलत' },
  { en: 'Yard', ne: 'आँगन' },
  { en: 'Yellow', ne: 'पहेंलो' },
  { en: 'Yesterday', ne: 'हिजो' },
  { en: 'Yet', ne: 'अझै' },
  { en: 'You', ne: 'तिमी/तपाईं' },
  { en: 'Young', ne: 'जवान' },
  { en: 'Your', ne: 'तिम्रो/तपाईंको' },
  { en: 'Zebra', ne: 'जेब्रा' },
  { en: 'Zinc', ne: 'जिंक' },
  { en: 'Zoom', ne: 'जुम' },
  { en: 'Abroad', ne: 'विदेशमा' },
  { en: 'Absence', ne: 'अनुपस्थिति' },
  { en: 'Absolute', ne: 'पूर्ण' },
  { en: 'Academic', ne: 'शैक्षिक' },
  { en: 'Acceptable', ne: 'स्वीकार्य' },
  { en: 'Access', ne: 'पहुँच' },
  { en: 'Accommodation', ne: 'बसोबास' },
  { en: 'Accountable', ne: 'जिम्मेवार' },
  { en: 'Accurate', ne: 'सटीक' },
  { en: 'Active', ne: 'सक्रिय' },
  { en: 'Admit', ne: 'स्वीकार गर्नु' },
  { en: 'Agriculture', ne: 'कृषि' },
  { en: 'Alarm', ne: 'अलार्म' },
  { en: 'Alcohol', ne: 'मदिरा' },
  { en: 'Align', ne: 'मिलाउनु' },
  { en: 'Alive', ne: 'जीवित' },
  { en: 'Almost', ne: 'लगभग' },
  { en: 'Along', ne: 'सँगै' },
  { en: 'Already', ne: 'पहिले नै' },
  { en: 'Alternative', ne: 'विकल्प' },
  { en: 'Amazing', ne: 'अचम्मको' },
  { en: 'Amount', ne: 'मात्रा' },
  { en: 'Ancient', ne: 'प्राचीन' },
  { en: 'Anxious', ne: 'चिन्तित' },
  { en: 'Anywhere', ne: 'जहाँसुकै' },
  { en: 'Apart', ne: 'अलग' },
  { en: 'Apologize', ne: 'माफी माग्नु' },
  { en: 'Approximate', ne: 'अनुमानित' },
  { en: 'Army', ne: 'सेना' },
  { en: 'Artist', ne: 'कलाकार' },
  { en: 'Asleep', ne: 'सुतिरहेको' },
  { en: 'Assembly', ne: 'सभा' },
  { en: 'Athlete', ne: 'खेलाडी' },
  { en: 'Average', ne: 'औसत' },
  { en: 'Band', ne: 'समूह' },
  { en: 'Battle', ne: 'युद्ध' },
  { en: 'Beyond', ne: 'पर' },
  { en: 'Billion', ne: 'अरब' },
  { en: 'Border', ne: 'सीमा' },
  { en: 'Brain', ne: 'मस्तिष्क' },
  { en: 'Brand', ne: 'ब्रान्ड' },
  { en: 'Brave', ne: 'बहादुर' },
  { en: 'Bridge', ne: 'पुल' },
  { en: 'Bright', ne: 'उज्यालो' },
  { en: 'Bullet', ne: 'गोली' },
  { en: 'Burn', ne: 'जल्नु' },
  { en: 'Cable', ne: 'केबल' },
  { en: 'Cancel', ne: 'रद्द गर्नु' },
  { en: 'Cancer', ne: 'क्यान्सर' },
  { en: 'Capacity', ne: 'क्षमता' },
  { en: 'Careful', ne: 'सावधान' },
  { en: 'Carpet', ne: 'कार्पेट' },
  { en: 'Ceremony', ne: 'समारोह' },
  { en: 'Champion', ne: 'विजेता' },
  { en: 'Chance', ne: 'मौका' },
  { en: 'Charity', ne: 'दान' },
  { en: 'Chart', ne: 'चार्ट' },
  { en: 'Cheap', ne: 'सस्तो' },
  { en: 'Cheer', ne: 'उत्साह' },
  { en: 'Chemical', ne: 'रसायन' },
  { en: 'Childish', ne: 'बालसुलभ' },
  { en: 'Church', ne: 'चर्च' },
  { en: 'Circle', ne: 'वृत्त' },
  { en: 'Claim', ne: 'दाबी गर्नु' },
  { en: 'Class', ne: 'कक्षा' },
  { en: 'Classic', ne: 'शास्त्रीय' },
  { en: 'Cleanliness', ne: 'सफाइ' },
  { en: 'Clever', ne: 'चलाख' },
  { en: 'Clock', ne: 'घडी' },
  { en: 'Cloud', ne: 'बादल' },
  { en: 'Club', ne: 'क्लब' },
  { en: 'Coach', ne: 'प्रशिक्षक' },
  { en: 'Coast', ne: 'तट' },
  { en: 'Code', ne: 'कोड' },
  { en: 'Coffee', ne: 'कफी' },
  { en: 'Coin', ne: 'सिक्का' },
  { en: 'Coldness', ne: 'चिसोपन' },
  { en: 'College', ne: 'कलेज' },
  { en: 'Commercial', ne: 'व्यापारिक' },
  { en: 'Common', ne: 'सामान्य' },
  { en: 'Complex', ne: 'जटिल' },
  { en: 'Component', ne: 'भाग' },
  { en: 'Compose', ne: 'रचना गर्नु' },
  { en: 'Computer', ne: 'कम्प्युटर' },
  { en: 'Concert', ne: 'कन्सर्ट' },
  { en: 'Conference', ne: 'सम्मेलन' },
  { en: 'Constant', ne: 'निरन्तर' },
  { en: 'Container', ne: 'भाँडो / कन्टेनर' },
  { en: 'Content', ne: 'सामग्री' },
  { en: 'Corner', ne: 'कुना' },
  { en: 'Cotton', ne: 'कपास' },
  { en: 'Council', ne: 'परिषद' },
  { en: 'Countrywide', ne: 'देशव्यापी' },
  { en: 'Couple', ne: 'जोडी' },
  { en: 'Courage', ne: 'साहस' },
  { en: 'Course', ne: 'पाठ्यक्रम' },
  { en: 'Court', ne: 'अदालत' },
  { en: 'Crime', ne: 'अपराध' },
  { en: 'Critic', ne: 'आलोचक' },
  { en: 'Curious', ne: 'जिज्ञासु' },
  { en: 'Current', ne: 'वर्तमान' },
  { en: 'Danger', ne: 'खतरा' },
  { en: 'Debt', ne: 'ऋण' },
  { en: 'Decline', ne: 'घट्नु' },
  { en: 'Deepen', ne: 'गहिरो बनाउनु' },
  { en: 'Defeat', ne: 'हार' },
  { en: 'Diary', ne: 'डायरी' },
  { en: 'Dictionary', ne: 'शब्दकोश' },
  { en: 'Different', ne: 'फरक' },
  { en: 'Difficult', ne: 'कठिन' },
  { en: 'Digital', ne: 'डिजिटल' },
  { en: 'Dirty', ne: 'फोहोर' },
  { en: 'Disaster', ne: 'विपत्ति' },
  { en: 'District', ne: 'जिल्ला' },
  { en: 'Doctor', ne: 'डाक्टर' },
  { en: 'Dollar', ne: 'डलर' },
  { en: 'Downward', ne: 'तलतिर' },
  { en: 'Drama', ne: 'नाटक' },
  { en: 'Dress', ne: 'लुगा' },
  { en: 'Drinkable', ne: 'पिउन योग्य' },
  { en: 'Driver', ne: 'चालक' },
  { en: 'Dropout', ne: 'छोड्ने' },
  { en: 'Drug', ne: 'औषधि' },
  { en: 'Dryness', ne: 'सुक्खापन' },
  { en: 'Duty', ne: 'कर्तव्य' },
  { en: 'Dynamic', ne: 'गतिशील' },
  { en: 'Earthquake', ne: 'भूकम्प' },
  { en: 'Economic', ne: 'आर्थिक' },
  { en: 'Edgewise', ne: 'किनारामा' },
  { en: 'Edit', ne: 'सम्पादन गर्नु' },
  { en: 'Effective', ne: 'प्रभावकारी' },
  { en: 'Efficient', ne: 'दक्ष' },
  { en: 'Elastic', ne: 'लचकदार' },
  { en: 'Elder', ne: 'ज्येष्ठ' },
  { en: 'Election', ne: 'चुनाव' },
  { en: 'Employee', ne: 'कर्मचारी' },
  { en: 'Employer', ne: 'रोजगारदाता' },
  { en: 'Endure', ne: 'सहनु' },
  { en: 'Enemy', ne: 'शत्रु' },
  { en: 'Engage', ne: 'संलग्न हुनु' },
  { en: 'Engineered', ne: 'इन्जिनियर गरिएको' },
  { en: 'Enormous', ne: 'विशाल' },
  { en: 'Equalize', ne: 'बराबरी गर्नु' },
  { en: 'Exact', ne: 'ठ्याक्कै' },
  { en: 'Excellent', ne: 'उत्कृष्ट' },
  { en: 'Exciting', ne: 'रोमाञ्चक' },
  { en: 'Exhaust', ne: 'थाक्नु' },
  { en: 'Expedition', ne: 'अभियान' },
  { en: 'Export', ne: 'निर्यात' },
  { en: 'Extreme', ne: 'चरम' },
  { en: 'Fabric', ne: 'कपडा' },
  { en: 'Familiar', ne: 'परिचित' },
  { en: 'Fantastic', ne: 'शानदार' },
  { en: 'Fashion', ne: 'फेसन' },
  { en: 'Federal', ne: 'संघीय' },
  { en: 'Flexible', ne: 'लचिलो' },
  { en: 'Flourish', ne: 'फस्टाउनु' },
  { en: 'Forecast', ne: 'पूर्वानुमान' },
  { en: 'Fraction', ne: 'अंश' },
  { en: 'Framework', ne: 'संरचना' },
  { en: 'Fundamental', ne: 'आधारभूत' },
  { en: 'Furniture', ne: 'फर्निचर' },
  { en: 'Galaxy', ne: 'आकाशगंगा' },
  { en: 'Gallery', ne: 'ग्यालरी' },
  { en: 'Geography', ne: 'भूगोल' },
  { en: 'Gesture', ne: 'इशारा' },
  { en: 'Global', ne: 'वैश्विक' },
  { en: 'Graduate', ne: 'स्नातक' },
  { en: 'Gravity', ne: 'गुरुत्वाकर्षण' },
  { en: 'Guarantee', ne: 'ग्यारेन्टी' },
  { en: 'Harvest', ne: 'बाली' },
  { en: 'Hazard', ne: 'खतरा' },
  { en: 'Holiday', ne: 'बिदा' },
  { en: 'Horizon', ne: 'क्षितिज' },
  { en: 'Immigrant', ne: 'आप्रवासी' },
  { en: 'Import', ne: 'आयात' },
  { en: 'Impression', ne: 'प्रभाव' },
  { en: 'Inclusion', ne: 'समावेश' },
  { en: 'Index', ne: 'सूची' },
  { en: 'Ingredient', ne: 'सामग्री' },
  { en: 'Initial', ne: 'प्रारम्भिक' },
  { en: 'Insert', ne: 'घुसाउनु' },
  { en: 'Institution', ne: 'संस्था' },
  { en: 'Interrupt', ne: 'अवरोध गर्नु' },
  { en: 'Interval', ne: 'अन्तराल' },
  { en: 'Knowledgeable', ne: 'ज्ञानी' },
  { en: 'Laboratory', ne: 'प्रयोगशाला' },
  { en: 'Landscape', ne: 'परिदृश्य' },
  { en: 'Leisure', ne: 'फुर्सद' },
  { en: 'Liberal', ne: 'उदार' },
  { en: 'Liberty', ne: 'स्वतन्त्रता' },
  { en: 'Logical', ne: 'तार्किक' },
  { en: 'Magnificent', ne: 'भव्य' },
  { en: 'Maintenance', ne: 'मर्मतसम्भार' },
  { en: 'Majority', ne: 'बहुमत' },
  { en: 'Manufacture', ne: 'उत्पादन गर्नु' },
  { en: 'Materialism', ne: 'भौतिकवाद' },
  { en: 'Meaning', ne: 'अर्थ' },
  { en: 'Membership', ne: 'सदस्यता' },
  { en: 'Mental', ne: 'मानसिक' },
  { en: 'Mobility', ne: 'चलायमानता' },
  { en: 'Neutral', ne: 'तटस्थ' },
  { en: 'Notation', ne: 'संकेत' },
  { en: 'Opinionated', ne: 'विचारधारी' },
  { en: 'Optimism', ne: 'आशावाद' },
  { en: 'Photography', ne: 'फोटोग्राफी' },
  { en: 'Frankly', ne: 'खुलस्त रूपमा' },
  { en: 'Pride', ne: 'गर्व' },
  { en: 'Primary', ne: 'प्राथमिक' },
  { en: 'Proceed', ne: 'अगाडि बढ्नु' },
  { en: 'Proper', ne: 'उचित' },
  { en: 'Propose', ne: 'प्रस्ताव राख्नु' },
  { en: 'Prosper', ne: 'समृद्ध हुनु' },
  { en: 'Purchase', ne: 'खरिद गर्नु' },
  { en: 'Pursue', ne: 'पछ्याउनु' },
  { en: 'Quietness', ne: 'शान्तता' },
  { en: 'Radical', ne: 'मूलभूत परिवर्तनकारी' },
  { en: 'Railway', ne: 'रेलमार्ग' },
  { en: 'Random', ne: 'अनियमित' },
  { en: 'Rapid', ne: 'छिटो' },
  { en: 'Reasonable', ne: 'उचित' },
  { en: 'Rebel', ne: 'विद्रोही' },
  { en: 'Rebuild', ne: 'पुनर्निर्माण गर्नु' },
  { en: 'Recall', ne: 'सम्झनु' },
  { en: 'Reception', ne: 'स्वागत' },
  { en: 'Recruit', ne: 'भर्ती गर्नु' },
  { en: 'Regard', ne: 'मान्नु' },
  { en: 'Register', ne: 'दर्ता गर्नु' },
  { en: 'Regular', ne: 'नियमित' },
  { en: 'Relax', ne: 'आराम गर्नु' },
  { en: 'Remedy', ne: 'उपचार' },
  { en: 'Rescue', ne: 'उद्धार गर्नु' },
  { en: 'Resemble', ne: 'मिल्दोल्दो हुनु' },
  { en: 'Retire', ne: 'सेवानिभृत्त हुनु' },
  { en: 'Revenue', ne: 'आम्दानी' },
  { en: 'Reverse', ne: 'उल्टो गर्नु' },
  { en: 'Rhythm', ne: 'लय' },
  { en: 'Rival', ne: 'प्रतिस्पर्धी' },
  { en: 'Roadmap', ne: 'मार्गचित्र' },
  { en: 'Rural', ne: 'ग्रामीण' },
  { en: 'Satisfy', ne: 'सन्तुष्ट पार्नु' },
  { en: 'Scientific', ne: 'वैज्ञानिक' },
  { en: 'Segment', ne: 'खण्ड' },
  { en: 'Selfish', ne: 'स्वार्थी' },
  { en: 'Senior', ne: 'वरिष्ठ' },
  { en: 'Sensible', ne: 'समझदार' },
  { en: 'Sequence', ne: 'क्रम' },
  { en: 'Seriousness', ne: 'गम्भीरता' },
  { en: 'Severe', ne: 'गम्भीर' },
  { en: 'Shadow', ne: 'छायाँ' },
  { en: 'Shareholder', ne: 'सेयरधनी' },
  { en: 'Shelter', ne: 'आश्रय' },
  { en: 'Shift', ne: 'सार्नु' },
  { en: 'Similar', ne: 'मिल्दोल्दो' },
  { en: 'Skillful', ne: 'दक्ष' },
  { en: 'Strength', ne: 'शक्ति' },
  { en: 'Struggle', ne: 'संघर्ष' },
  { en: 'Subjective', ne: 'व्यक्तिगत' },
  { en: 'Substitute', ne: 'विकल्प' },
  { en: 'Successor', ne: 'उत्तराधिकारी' },
  { en: 'Supervise', ne: 'निरीक्षण गर्नु' },
  { en: 'Surround', ne: 'वरिपरि घेरिनु' },
  { en: 'Sympathy', ne: 'सहानुभूति' },
  { en: 'Talent', ne: 'प्रतिभा' },
  { en: 'Technical', ne: 'प्राविधिक' },
  { en: 'Transform', ne: 'परिवर्तन गर्नु' },
  { en: 'Translate', ne: 'अनुवाद गर्नु' },
  { en: 'Tribe', ne: 'जनजाति' },
  { en: 'Trigger', ne: 'सुरु गराउनु' },
  { en: 'Triumph', ne: 'विजय' },
  { en: 'Trustworthy', ne: 'विश्वासिलो' },
  { en: 'Ultimate', ne: 'अन्तिम' },
  { en: 'Unify', ne: 'एकीकृत गर्नु' },
  { en: 'Universe', ne: 'ब्रह्माण्ड' },
  { en: 'Urban', ne: 'शहरी' },
  { en: 'Urgent', ne: 'तत्काल' },
  { en: 'Validate', ne: 'प्रमाणित गर्नु' },
  { en: 'Valuable', ne: 'मूल्यवान' },
  { en: 'Variable', ne: 'परिवर्तनशील' },
  { en: 'Venture', ne: 'साहसिक प्रयास' },
  { en: 'Verify', ne: 'पुष्टि गर्नु' },
  { en: 'Vertical', ne: 'ठाडो' },
  { en: 'Violate', ne: 'उल्लंघन गर्नु' },
  { en: 'Virtual', ne: 'आभासी' },
  { en: 'Visible', ne: 'देखिने' },
  { en: 'Vital', ne: 'अत्यावश्यक' },
  { en: 'Vocabulary', ne: 'शव्दावली' },
  { en: 'Vulnerable', ne: 'कमजोर' },
  { en: 'Wander', ne: 'घुम्नु' },
  { en: 'Wealthy', ne: 'धनी' },
  { en: 'Website', ne: 'वेवसाइट' },
  { en: 'Whisper', ne: 'फुसफुसाउनु' },
  { en: 'Zeroes', ne: 'शून्यहरू' },
  { en: 'Zooming', ne: 'जुम गर्नु' },
  { en: 'Zonewise', ne: 'क्षेत्र अनुसार' },
];

export const intermediateVocabulary = [
  { en: 'Abnormal', ne: 'असामान्य' },
  { en: 'Abuse', ne: 'दुरुपयोग' },
  { en: 'Accessible', ne: 'पहुँचयोग्य' },
  { en: 'Accidentally', ne: 'आकस्मिक रूपमा' },
  { en: 'Accomplishment', ne: 'उपलब्धि' },
  { en: 'Adaptation', ne: 'अनुकूलन' },
  { en: 'Addiction', ne: 'लत' },
  { en: 'Additional', ne: 'थप' },
  { en: 'Adequately', ne: 'पर्याप्त रूपमा' },
  { en: 'Adjusted', ne: 'समायोजित' },
  { en: 'Administration', ne: 'प्रशासन' },
  { en: 'Admission', ne: 'प्रवेश' },
  { en: 'Adopted', ne: 'ग्रहण गरिएको' },
  { en: 'Advanced', ne: 'उन्नत' },
  { en: 'Advantageous', ne: 'लाभदायक' },
  { en: 'Adventure', ne: 'साहसिक कार्य' },
  { en: 'Adverse', ne: 'प्रतिकूल' },
  { en: 'Advertise', ne: 'विज्ञापन गर्नु' },
  { en: 'Advice', ne: 'सल्लाह' },
  { en: 'Aesthetic', ne: 'सौन्दर्यसम्बन्धी' },
  { en: 'Affection', ne: 'माया' },
  { en: 'Affordable', ne: 'सुलभ' },
  { en: 'Agency', ne: 'संस्था' },
  { en: 'Aggressive', ne: 'आक्रामक' },
  { en: 'Agreement', ne: 'सम्झौता' },
  { en: 'Alertness', ne: 'सतर्कता' },
  { en: 'Alienation', ne: 'अलगाव' },
  { en: 'Allowance', ne: 'भत्ता' },
  { en: 'Alteration', ne: 'परिवर्तन' },
  { en: 'Ambition', ne: 'महत्वाकांक्षा' },
  { en: 'Analysis', ne: 'विश्लेषण' },
  { en: 'Ancestor', ne: 'पूर्वज' },
  { en: 'Anger', ne: 'रिस' },
  { en: 'Anniversary', ne: 'वार्षिकोत्सव' },
  { en: 'Announcement', ne: 'घोषणा' },
  { en: 'Annual', ne: 'वार्षिक' },
  { en: 'Anxiety', ne: 'चिन्ता' },
  { en: 'Apology', ne: 'माफी' },
  { en: 'Apparent', ne: 'स्पष्ट देखिने' },
  { en: 'Appeal', ne: 'अपील' },
  { en: 'Appearance', ne: 'देखावट' },
  { en: 'Application', ne: 'आवेदन' },
  { en: 'Appointment', ne: 'नियुक्ति' },
  { en: 'Appreciation', ne: 'प्रशंसा' },
  { en: 'Approval', ne: 'स्वीकृति' },
  { en: 'Argument', ne: 'तर्क' },
  { en: 'Arrangement', ne: 'व्यवस्था' },
  { en: 'Arrival', ne: 'आगमन' },
  { en: 'Article', ne: 'लेख' },
  { en: 'Artificial', ne: 'कृत्रिम' },
  { en: 'Aspect', ne: 'पक्ष' },
  { en: 'Assignment', ne: 'कार्य' },
  { en: 'Assistance', ne: 'सहयोग' },
  { en: 'Assurance', ne: 'सुनिश्चितता' },
  { en: 'Atmosphere', ne: 'वातावरण' },
  { en: 'Attachment', ne: 'संलग्नता' },
  { en: 'Attention', ne: 'ध्यान' },
  { en: 'Attitude', ne: 'दृष्टिकोण' },
  { en: 'Attraction', ne: 'आकर्षण' },
  { en: 'Automatic', ne: 'स्वचालित' },
  { en: 'Barrier', ne: 'अवरोध' },
  { en: 'Behavior', ne: 'व्यवहार' },
  { en: 'Belief', ne: 'विश्वास' },
  { en: 'Biology', ne: 'जीवविज्ञान' },
  { en: 'Boundary', ne: 'सीमा' },
  { en: 'Branch', ne: 'शाखा' },
  { en: 'Breakdown', ne: 'विघटन' },
  { en: 'Breath', ne: 'सास' },
  { en: 'Budget', ne: 'बजेट' },
  { en: 'Burden', ne: 'बोझ' },
  { en: 'Calculation', ne: 'गणना' },
  { en: 'Campaign', ne: 'अभियान' },
  { en: 'Capability', ne: 'क्षमता' },
  { en: 'Capital', ne: 'राजधानी' },
  { en: 'Career', ne: 'करियर' },
  { en: 'Category', ne: 'वर्ग' },
  { en: 'Celebration', ne: 'उत्सव' },
  { en: 'Characteristic', ne: 'विशेषता' },
  { en: 'Choice', ne: 'छनोट' },
  { en: 'Circumstance', ne: 'परिस्थिति' },
  { en: 'Citizen', ne: 'नागरिक' },
  { en: 'Civilization', ne: 'सभ्यता' },
  { en: 'Clarification', ne: 'स्पष्टिकरण' },
  { en: 'Classification', ne: 'वर्गीकरण' },
  { en: 'Climate', ne: 'जलवायु' },
  { en: 'Combination', ne: 'संयोजन' },
  { en: 'Comfort', ne: 'आराम' },
  { en: 'Commentary', ne: 'टिप्पणी' },
  { en: 'Community', ne: 'समुदाय' },
  { en: 'Competition', ne: 'प्रतिस्पर्धा' },
  { en: 'Complaint', ne: 'गुनासो' },
  { en: 'Compromise', ne: 'सम्झौता' },
  { en: 'Concept', ne: 'अवधारणा' },
  { en: 'Concern', ne: 'चिन्ता' },
  { en: 'Conclusion', ne: 'निष्कर्ष' },
  { en: 'Condition', ne: 'अवस्था' },
  { en: 'Confidence', ne: 'आत्मविश्वास' },
  { en: 'Confirmation', ne: 'पुष्टि' },
  { en: 'Conflict', ne: 'द्वन्द्व' },
  { en: 'Connection', ne: 'सम्बन्ध' },
  { en: 'Consequence', ne: 'परिणाम' },
  { en: 'Conservation', ne: 'संरक्षण' },
  { en: 'Consideration', ne: 'विचार' },
  { en: 'Consistency', ne: 'स्थिरता' },
  { en: 'Construction', ne: 'निर्माण' },
  { en: 'Consumer', ne: 'उपभोक्ता' },
  { en: 'Context', ne: 'सन्दर्भ' },
  { en: 'Convenience', ne: 'सुविधा' },
  { en: 'Convention', ne: 'परम्परा' },
  { en: 'Conversation', ne: 'कुराकानी' },
  { en: 'Cooperation', ne: 'सहकार्य' },
  { en: 'Credit', ne: 'ऋण' },
  { en: 'Crisis', ne: 'संकट' },
  { en: 'Criterion', ne: 'मापदण्ड' },
  { en: 'Criticism', ne: 'आलोचना' },
  { en: 'Culture', ne: 'संस्कृति' },
  { en: 'Customer', ne: 'ग्राहक' },
  { en: 'Data', ne: 'तथ्यांक' },
  { en: 'Decision', ne: 'निर्णय' },
  { en: 'Degree', ne: 'डिग्री' },
  { en: 'Delivery', ne: 'वितरण' },
  { en: 'Democracy', ne: 'लोकतन्त्र' },
  { en: 'Demonstration', ne: 'प्रदर्शन' },
  { en: 'Density', ne: 'घनत्व' },
  { en: 'Department', ne: 'विभाग' },
  { en: 'Dependency', ne: 'निर्भरता' },
  { en: 'Description', ne: 'वर्णन' },
  { en: 'Desire', ne: 'इच्छा' },
  { en: 'Destination', ne: 'गन्तव्य' },
  { en: 'Detail', ne: 'विवरण' },
  { en: 'Development', ne: 'विकास' },
  { en: 'Device', ne: 'उपकरण' },
  { en: 'Difference', ne: 'फरक' },
  { en: 'Difficulty', ne: 'कठिनाइ' },
  { en: 'Direction', ne: 'दिशा' },
  { en: 'Discipline', ne: 'अनुशासन' },
  { en: 'Discovery', ne: 'खोज' },
  { en: 'Discussion', ne: 'छलफल' },
  { en: 'Disease', ne: 'रोग' },
  { en: 'Distance', ne: 'दूरी' },
  { en: 'Diversity', ne: 'विविधता' },
  { en: 'Document', ne: 'कागजात' },
  { en: 'Domestic', ne: 'घरेलु' },
  { en: 'Dominance', ne: 'प्रभुत्व' },
  { en: 'Duration', ne: 'अवधि' },
  { en: 'Economy', ne: 'अर्थतन्त्र' },
  { en: 'Education', ne: 'शिक्षा' },
  { en: 'Efficiency', ne: 'दख्ता' },
  { en: 'Element', ne: 'तत्व' },
  { en: 'Emergency', ne: 'आपतकाल' },
  { en: 'Emotion', ne: 'भावना' },
  { en: 'Emphasis', ne: 'जोड' },
  { en: 'Employment', ne: 'रोजगारी' },
  { en: 'Enable', ne: 'सक्षम बनाउनु' },
  { en: 'Encouragement', ne: 'प्रोत्साहन' },
  { en: 'Endurance', ne: 'सहनशीलता' },
  { en: 'Energy', ne: 'ऊर्जा' },
  { en: 'Engagement', ne: 'संलग्नता' },
  { en: 'Enrollment', ne: 'भर्ना' },
  { en: 'Enterprise', ne: 'उद्यम' },
  { en: 'Entertainment', ne: 'मनोरञ्जन' },
  { en: 'Enthusiasm', ne: 'उत्साह' },
  { en: 'Environment', ne: 'वातावरण' },
  { en: 'Equality', ne: 'समानता' },
  { en: 'Equipment', ne: 'उपकरण' },
  { en: 'Error', ne: 'त्रुटि' },
  { en: 'Establishment', ne: 'स्थापना' },
  { en: 'Evaluation', ne: 'मूल्याङ्कन' },
  { en: 'Evidence', ne: 'प्रमाण' },
  { en: 'Evolution', ne: 'विकासक्रम' },
  { en: 'Examination', ne: 'परीक्षा' },
  { en: 'Example', ne: 'उदाहरण' },
  { en: 'Exception', ne: 'अपवाद' },
  { en: 'Excitement', ne: 'उत्साह' },
  { en: 'Execution', ne: 'कार्यान्वयन' },
  { en: 'Expansion', ne: 'विस्तार' },
  { en: 'Expectation', ne: 'अपेक्षा' },
  { en: 'Explanation', ne: 'व्याख्या' },
  { en: 'Exploration', ne: 'अन्वेषण' },
  { en: 'Expression', ne: 'अभिव्यक्ति' },
  { en: 'Extension', ne: 'विस्तार' },
  { en: 'External', ne: 'बाह्य' },
  { en: 'Factor', ne: 'तत्व' },
  { en: 'Failure', ne: 'असफलता' },
  { en: 'Familiarity', ne: 'परिचितता' },
  { en: 'Feature', ne: 'विशेषता' },
  { en: 'Feedback', ne: 'प्रतिक्रिया' },
  { en: 'Feeling', ne: 'भावना' },
  { en: 'Fiction', ne: 'काल्पनिक कथा' },
  { en: 'Field', ne: 'क्षेत्र' },
  { en: 'Finding', ne: 'निष्कर्ष' },
  { en: 'Fitness', ne: 'तन्दुरुस्ती' },
  { en: 'Flexibility', ne: 'लचिलोपन' },
  { en: 'Formation', ne: 'गठन' },
  { en: 'Foundation', ne: 'आधार' },
  { en: 'Freedom', ne: 'स्वतन्त्रता' },
  { en: 'Frequency', ne: 'आवृत्ति' },
  { en: 'Friendship', ne: 'मित्रता' },
  { en: 'Function', ne: 'कार्य' },
  { en: 'Funding', ne: 'वित्तपोषण' },
  { en: 'Future', ne: 'भविष्य' },
  { en: 'Generation', ne: 'पुस्ता' },
  { en: 'Goal', ne: 'लक्ष्य' },
  { en: 'Government', ne: 'सरकार' },
  { en: 'Growth', ne: 'वृद्धि' },
  { en: 'Guidance', ne: 'मार्गदर्शन' },
  { en: 'Habit', ne: 'बानी' },
  { en: 'Happiness', ne: 'खुशी' },
  { en: 'Harm', ne: 'हानि' },
  { en: 'Health', ne: 'स्वास्थ्य' },
  { en: 'Hearing', ne: 'श्रवण' },
  { en: 'Heritage', ne: 'सम्पदा' },
  { en: 'Hierarchy', ne: 'श्रेणीक्रम' },
  { en: 'Highlight', ne: 'मुख्य बिन्दु' },
  { en: 'History', ne: 'इतिहास' },
  { en: 'Honesty', ne: 'इमानदारी' },
  { en: 'Hospitality', ne: 'आतिथ्य' },
  { en: 'Human', ne: 'मानव' },
  { en: 'Humour', ne: 'हास्य' },
  { en: 'Hypothesis', ne: 'परिकल्पना' },
  { en: 'Idea', ne: 'विचार' },
  { en: 'Identity', ne: 'पहिचान' },
  { en: 'Illustration', ne: 'चित्रण' },
  { en: 'Image', ne: 'छवि' },
  { en: 'Imagination', ne: 'कल्पना' },
  { en: 'Impact', ne: 'प्रभाव' },
  { en: 'Implementation', ne: 'कार्यान्वयन' },
  { en: 'Importance', ne: 'महत्व' },
  { en: 'Improvement', ne: 'सुधार' },
  { en: 'Incentive', ne: 'प्रोत्साहन' },
  { en: 'Income', ne: 'आय' },
  { en: 'Independence', ne: 'स्वतन्त्रता' },
  { en: 'Indicator', ne: 'सूचक' },
  { en: 'Industry', ne: 'उद्योग' },
  { en: 'Information', ne: 'जानकारी' },
  { en: 'Innovation', ne: 'नवप्रवर्तन' },
  { en: 'Input', ne: 'इनपुट' },
  { en: 'Inquiry', ne: 'सोधपुछ' },
  { en: 'Insight', ne: 'अन्तरदृष्टि' },
  { en: 'Inspiration', ne: 'प्रेरणा' },
  { en: 'Installation', ne: 'स्थापना' },
  { en: 'Instance', ne: 'उदाहरण' },
  { en: 'Instruction', ne: 'निर्देशन' },
  { en: 'Insurance', ne: 'बीमा' },
  { en: 'Integration', ne: 'एकीकरण' },
  { en: 'Intelligence', ne: 'बुद्धिमत्ता' },
  { en: 'Interaction', ne: 'अन्तरक्रिया' },
  { en: 'Internal', ne: 'आन्तरिक' },
  { en: 'Interpretation', ne: 'व्याख्या' },
  { en: 'Intervention', ne: 'हस्तक्षेप' },
  { en: 'Introduction', ne: 'परिचय' },
  { en: 'Investment', ne: 'लगानी' },
  { en: 'Investigation', ne: 'अनुसन्धान' },
  { en: 'Involvement', ne: 'संलग्नता' },
  { en: 'Issue', ne: 'मुद्दा' },
  { en: 'Item', ne: 'वस्तु' },
  { en: 'Judgment', ne: 'निर्णय' },
  { en: 'Justice', ne: 'न्याय' },
  { en: 'Knowledge', ne: 'ज्ञान' },
  { en: 'Labor', ne: 'श्रम' },
  { en: 'Language', ne: 'भाषा' },
  { en: 'Leadership', ne: 'नेतृत्व' },
  { en: 'Learning', ne: 'सिकाइ' },
  { en: 'Lecture', ne: 'व्याख्यान' },
  { en: 'Legal', ne: 'कानुनी' },
  { en: 'Lesson', ne: 'पाठ' },
  { en: 'Library', ne: 'पुस्तकालय' },
  { en: 'Lifestyle', ne: 'जीवनशैली' },
  { en: 'Limitation', ne: 'सीमा' },
  { en: 'Literacy', ne: 'साक्षरता' },
  { en: 'Literature', ne: 'साहित्य' },
  { en: 'Location', ne: 'स्थान' },
  { en: 'Logic', ne: 'तर्क' },
  { en: 'Loyalty', ne: 'निष्ठा' },
  { en: 'Machinery', ne: 'मेसिनरी' },
  { en: 'Management', ne: 'व्यवस्थापन' },
  { en: 'Manufacturer', ne: 'उत्पादक' },
  { en: 'Marketing', ne: 'बजार व्यवस्थापन' },
  { en: 'Material', ne: 'सामग्री' },
  { en: 'Mathematics', ne: 'गणित' },
  { en: 'Measurement', ne: 'मापन' },
  { en: 'Mechanism', ne: 'संयन्त्र' },
  { en: 'Media', ne: 'सञ्चार माध्यम' },
  { en: 'Medicine', ne: 'औषधि' },
  { en: 'Memory', ne: 'स्मृति' },
  { en: 'Mentality', ne: 'मानसिकता' },
  { en: 'Message', ne: 'सन्देश' },
  { en: 'Method', ne: 'विधि' },
  { en: 'Migration', ne: 'बसाइँसराइ' },
  { en: 'Mindset', ne: 'मानसिक सोच' },
  { en: 'Minimum', ne: 'न्यूनतम' },
  { en: 'Mission', ne: 'मिशन' },
  { en: 'Modification', ne: 'परिवर्तन' },
  { en: 'Monitoring', ne: 'निगरानी' },
  { en: 'Motivation', ne: 'प्रेरणा' },
  { en: 'Movement', ne: 'आन्दोलन' },
  { en: 'Mutual', ne: 'पारस्परिक' },
  { en: 'Narrative', ne: 'कथा' },
  { en: 'Nation', ne: 'राष्ट्र' },
  { en: 'Nature', ne: 'प्रकृति' },
  { en: 'Navigation', ne: 'नेभिगेसन' },
  { en: 'Necessity', ne: 'आवश्यकता' },
  { en: 'Negotiation', ne: 'वार्ता' },
  { en: 'Network', ne: 'सञ्जाल' },
  { en: 'Neutrality', ne: 'तटस्थता' },
  { en: 'Nomination', ne: 'नामांकन' },
  { en: 'Normality', ne: 'सामान्य अवस्था' },
  { en: 'Notification', ne: 'सूचना' },
  { en: 'Nutrition', ne: 'पोषण' },
  { en: 'Object', ne: 'वस्तु' },
  { en: 'Objective', ne: 'उद्देश्य' },
  { en: 'Observation', ne: 'अवलोकन' },
  { en: 'Occupation', ne: 'पेशा' },
  { en: 'Occurrence', ne: 'घटना' },
  { en: 'Operation', ne: 'सञ्चालन' },
  { en: 'Opinion', ne: 'विचार' },
  { en: 'Opportunity', ne: 'अवसर' },
  { en: 'Opposition', ne: 'विरोध' },
  { en: 'Option', ne: 'विकल्प' },
  { en: 'Organization', ne: 'संगठन' },
  { en: 'Orientation', ne: 'अभिमुखीकरण' },
  { en: 'Outcome', ne: 'परिणाम' },
  { en: 'Output', ne: 'उत्पादन' },
  { en: 'Ownership', ne: 'स्वामित्व' },
  { en: 'Package', ne: 'प्याकेज' },
  { en: 'Pandemic', ne: 'महामारी' },
  { en: 'Panel', ne: 'समूह' },
  { en: 'Participation', ne: 'सहभागिता' },
  { en: 'Partnership', ne: 'साझेदारी' },
  { en: 'Performance', ne: 'प्रदर्शन' },
  { en: 'Permission', ne: 'अनुमति' },
  { en: 'Perspective', ne: 'दृष्टिकोण' },
  { en: 'Phenomenon', ne: 'घटना' },
  { en: 'Philosophy', ne: 'दर्शन' },
  { en: 'Physical', ne: 'भौतिक' },
  { en: 'Planning', ne: 'योजना बनाउने प्रक्रिया' },
  { en: 'Platform', ne: 'प्लेटफर्म' },
  { en: 'Policy', ne: 'नीति' },
  { en: 'Pollution', ne: 'प्रदूषण' },
  { en: 'Population', ne: 'जनसंख्या' },
  { en: 'Portfolio', ne: 'पोर्टफोलियो' },
  { en: 'Position', ne: 'स्थिति' },
  { en: 'Positive', ne: 'सकारात्मक' },
  { en: 'Possession', ne: 'स्वामित्व' },
  { en: 'Potential', ne: 'सम्भावना' },
  { en: 'Prediction', ne: 'पूर्वानुमान' },
  { en: 'Preference', ne: 'प्राथमिकता' },
  { en: 'Preparation', ne: 'तयारी' },
  { en: 'Presence', ne: 'उपस्थिति' },
  { en: 'Pressure', ne: 'दबाब' },
  { en: 'Prevention', ne: 'रोकथाम' },
  { en: 'Principle', ne: 'सिद्धान्त' },
  { en: 'Priority', ne: 'प्राथमिकता' },
  { en: 'Privacy', ne: 'गोपनीयता' },
  { en: 'Procedure', ne: 'प्रक्रिया' },
  { en: 'Process', ne: 'प्रक्रिया' },
  { en: 'Product', ne: 'उत्पादन' },
  { en: 'Production', ne: 'उत्पादन' },
  { en: 'Profession', ne: 'पेशा' },
  { en: 'Profile', ne: 'प्रोफाइल' },
  { en: 'Profit', ne: 'नाफा' },
  { en: 'Progress', ne: 'प्रगति' },
  { en: 'Project', ne: 'परियोजना' },
  { en: 'Promotion', ne: 'प्रवर्द्धन' },
  { en: 'Proof', ne: 'प्रमाण' },
  { en: 'Property', ne: 'सम्पत्ति' },
  { en: 'Proposal', ne: 'प्रस्ताव' },
  { en: 'Protection', ne: 'सुरक्षा' },
  { en: 'Protest', ne: 'विरोध' },
  { en: 'Provision', ne: 'व्यवस्था' },
  { en: 'Publicity', ne: 'प्रचार' },
  { en: 'Purpose', ne: 'उद्देश्य' },
  { en: 'Quality', ne: 'गुणस्तर' },
  { en: 'Quantity', ne: 'मात्रा' },
  { en: 'Reaction', ne: 'प्रतिक्रिया' },
  { en: 'Reality', ne: 'वास्तविकता' },
  { en: 'Reason', ne: 'कारण' },
  { en: 'Recognition', ne: 'पहिचान' },
  { en: 'Recommendation', ne: 'सिफारिस' },
  { en: 'Recovery', ne: 'पुनःप्राप्ति' },
  { en: 'Reduction', ne: 'कमी' },
  { en: 'Reference', ne: 'सन्दर्भ' },
  { en: 'Reflection', ne: 'प्रतिबिम्ब' },
  { en: 'Reform', ne: 'सुधार' },
  { en: 'Region', ne: 'क्षेत्र' },
  { en: 'Registration', ne: 'दर्ता' },
  { en: 'Regulation', ne: 'नियम' },
  { en: 'Relationship', ne: 'सम्बन्ध' },
  { en: 'Relief', ne: 'राहत' },
  { en: 'Religion', ne: 'धर्म' },
  { en: 'Remark', ne: 'टिप्पणी' },
  { en: 'Removal', ne: 'हटाउने प्रक्रिया' },
  { en: 'Replacement', ne: 'प्रतिस्थापन' },
  { en: 'Representation', ne: 'प्रतिनिधित्व' },
  { en: 'Request', ne: 'अनुरोध' },
  { en: 'Requirement', ne: 'आवश्यकता' },
  { en: 'Reservation', ne: 'आरक्षण' },
  { en: 'Resource', ne: 'स्रोत' },
  { en: 'Respect', ne: 'सम्मान' },
  { en: 'Response', ne: 'प्रतिक्रिया' },
  { en: 'Responsibility', ne: 'जिम्मेवारी' },
  { en: 'Role', ne: 'भूमिका' },
  { en: 'Routine', ne: 'दिनचर्या' },
  { en: 'Safety', ne: 'सुरक्षा' },
  { en: 'Salary', ne: 'तलव' },
  { en: 'Sample', ne: 'नमुना' },
  { en: 'Satisfaction', ne: 'सन्तुष्टि' },
  { en: 'Scenario', ne: 'परिदृश्य' },
  { en: 'Scholarship', ne: 'छात्रवृत्ति' },
  { en: 'Science', ne: 'विज्ञान' },
  { en: 'Security', ne: 'सुरक्षा' },
  { en: 'Selection', ne: 'छनोट' },
  { en: 'Service', ne: 'सेवा' },
  { en: 'Session', ne: 'सत्र' },
  { en: 'Settlement', ne: 'बसोबास' },
  { en: 'Situation', ne: 'अवस्था' },
  { en: 'Skill', ne: 'सीप' },
  { en: 'Society', ne: 'समाज' },
  { en: 'Solution', ne: 'समाधान' },
  { en: 'Source', ne: 'स्रोत' },
  { en: 'Strategy', ne: 'रणनीति' },
  { en: 'Structure', ne: 'संरचना' },
  { en: 'Success', ne: 'सफलता' },
  { en: 'Successful', ne: 'सफल' },
  { en: 'Sufficient', ne: 'पर्याप्त' },
  { en: 'Suggestion', ne: 'सुभाव' },
  { en: 'Summary', ne: 'सारांश' },
  { en: 'Supervision', ne: 'निरीक्षण' },
  { en: 'Surface', ne: 'सतह' },
  { en: 'Survey', ne: 'सर्वेक्षण' },
  { en: 'Survival', ne: 'बाँच्ने क्षमता' },
  { en: 'Symbol', ne: 'प्रतीक' },
  { en: 'System', ne: 'प्रणाली' },
  { en: 'Target', ne: 'लक्ष्य' },
  { en: 'Task', ne: 'कार्य' },
  { en: 'Technique', ne: 'प्रविधि' },
  { en: 'Technology', ne: 'प्रविधि' },
  { en: 'Temporary', ne: 'अस्थायी' },
  { en: 'Tension', ne: 'तनाव' },
  { en: 'Theory', ne: 'सिद्धान्त' },
  { en: 'Threat', ne: 'खतरा' },
  { en: 'Tradition', ne: 'परम्परा' },
  { en: 'Training', ne: 'प्रशिक्षण' },
  { en: 'Transaction', ne: 'लेनदेन' },
  { en: 'Transfer', ne: 'स्थानान्तरण' },
  { en: 'Transformation', ne: 'रूपान्तरण' },
  { en: 'Transition', ne: 'परिवर्तन' },
  { en: 'Translation', ne: 'अनुवाद' },
  { en: 'Transport', ne: 'यातायात' },
  { en: 'Trend', ne: 'प्रवृत्ति' },
  { en: 'Trial', ne: 'परीक्षण' },
  { en: 'Trust', ne: 'विश्वास' },
  { en: 'Understanding', ne: 'बुझाइ' },
  { en: 'Unemployment', ne: 'बेरोजगारी' },
  { en: 'Uniform', ne: 'पोशाक' },
  { en: 'Union', ne: 'संघ' },
  { en: 'Unique', ne: 'अद्वितीय' },
  { en: 'Unit', ne: 'एकाइ' },
  { en: 'Unity', ne: 'एकता' },
  { en: 'Universal', ne: 'सार्वभौमिक' },
  { en: 'Update', ne: 'अद्यावधिक' },
  { en: 'Upgrade', ne: 'सुधार' },
  { en: 'Usage', ne: 'प्रयोग' },
  { en: 'Utility', ne: 'उपयोगिता' },
  { en: 'Value', ne: 'मूल्य' },
  { en: 'Variation', ne: 'भिन्नता' },
  { en: 'Variety', ne: 'विविधता' },
  { en: 'Vehicle', ne: 'सवारी साधन' },
  { en: 'Version', ne: 'संस्करण' },
  { en: 'Victory', ne: 'विजय' },
  { en: 'Viewpoint', ne: 'दृष्टिकोण' },
  { en: 'Violence', ne: 'हिंसा' },
  { en: 'Vision', ne: 'दृष्टि' },
  { en: 'Visitor', ne: 'आगन्तुक' },
  { en: 'Volume', ne: 'आयतन' },
  { en: 'Volunteer', ne: 'स्वयंसेवक' },
  { en: 'Vote', ne: 'मतदान' },
  { en: 'Vulnerability', ne: 'कमजोरी' },
  { en: 'Wage', ne: 'ज्याला' },
  { en: 'Warning', ne: 'चेतावनी' },
  { en: 'Wealth', ne: 'सम्पत्ति' },
  { en: 'Welfare', ne: 'कल्याण' },
  { en: 'Willingness', ne: 'इच्छाशक्ति' },
  { en: 'Wisdom', ne: 'ज्ञान' },
  { en: 'Withdrawal', ne: 'फिर्ता' },
  { en: 'Witness', ne: 'साक्षी' },
  { en: 'Workforce', ne: 'श्रमशक्ति' },
  { en: 'Workshop', ne: 'कार्यशाला' },
  { en: 'Worth', ne: 'मूल्य' },
  { en: 'Writing', ne: 'लेखन' },
  { en: 'Youth', ne: 'युवा' },
  { en: 'Zeal', ne: 'उत्साह' },
  { en: 'Zone', ne: 'क्षेत्र' },
  { en: 'Adaptability', ne: 'अनुकूलता' },
  { en: 'Accountability', ne: 'जिम्मेवारी' },
  { en: 'Accuracy', ne: 'शुद्धता' },
  { en: 'Achievement', ne: 'उपलब्धि' },
  { en: 'Activeness', ne: 'सक्रियता' },
  { en: 'Adjustment', ne: 'समायोजन' },
  { en: 'Adoption', ne: 'ग्रहण' },
  { en: 'Advancement', ne: 'प्रगति' },
  { en: 'Advantage', ne: 'फाइदा' },
  { en: 'Advertisement', ne: 'विज्ञापन' },
  { en: 'Affordability', ne: 'वहन क्षमता' },
  { en: 'Aggression', ne: 'आक्रामकता' },
  { en: 'Allocation', ne: 'बाँडफाँड' },
  { en: 'Character', ne: 'चरित्र' },
  { en: 'Account', ne: 'खाता' },
  { en: 'Action', ne: 'कार्य' },
  { en: 'Addition', ne: 'थप' },
  { en: 'Address', ne: 'ठेगाना' },
  { en: 'Adequate', ne: 'पर्याप्त' },
  { en: 'Alien', ne: 'परदेशी' },
  { en: 'Allow', ne: 'अनुमति दिनु' },
  { en: 'Appoint', ne: 'नियुक्त गर्नु' },
  { en: 'Appropriate', ne: 'उपयुक्त' },
  { en: 'Associate', ne: 'सम्बन्धित गर्नु' },
  { en: 'Available', ne: 'उपलब्ध' },
  { en: 'Basic', ne: 'आधारभूत' },
  { en: 'Conscious', ne: 'सचेत' },
  { en: 'Consistent', ne: 'स्थिर' },
  { en: 'Correspond', ne: 'पत्राचार गर्नु' },
  { en: 'Practical', ne: 'व्यावहारिक' },
  { en: 'Precaution', ne: 'सावधानी' },
  { en: 'Prejudice', ne: 'पूर्वाग्रह' },
  { en: 'Preservation', ne: 'संरक्षण' },
  { en: 'Productivity', ne: 'उत्पादकता' },
  { en: 'Professional', ne: 'व्यावसायिक' },
  { en: 'Prohibition', ne: 'निषेध' },
  { en: 'Projection', ne: 'प्रक्षेपण' },
  { en: 'Prosperity', ne: 'समृद्धि' },
  { en: 'Psychology', ne: 'मनोविज्ञान' },
  { en: 'Publication', ne: 'प्रकाशन' },
  { en: 'Qualification', ne: 'योग्यता' },
  { en: 'Questionnaire', ne: 'प्र प्रश्नावली' },
  { en: 'Radiation', ne: 'विकिरण' },
  { en: 'Reconstruction', ne: 'पुनर्निर्माण' },
  { en: 'Recruitment', ne: 'भर्ती' },
  { en: 'Rehabilitation', ne: 'पुनर्वास' },
  { en: 'Reliability', ne: 'भरपर्दोपन' },
  { en: 'Renovation', ne: 'मर्मत सुधार' },
  { en: 'Resistance', ne: 'प्रतिरोध' },
  { en: 'Restriction', ne: 'प्रतिबन्ध' },
  { en: 'Revelation', ne: 'खुलासा' },
  { en: 'Revolution', ne: 'क्रान्ति' },
  { en: 'Sensitivity', ne: 'संवेदनशीलता' },
  { en: 'Separation', ne: 'पृथकीकरण' },
  { en: 'Significance', ne: 'महत्व' },
  { en: 'Simplification', ne: 'सरलीकरण' },
  { en: 'Socialization', ne: 'समाजीकरण' },
  { en: 'Specification', ne: 'विशेष विवरण' },
  { en: 'Stability', ne: 'स्थिरता' },
  { en: 'Standardization', ne: 'मानकीकरण' },
  { en: 'Strengthen', ne: 'बलियो बनाउनु' },
  { en: 'Submission', ne: 'प्रस्तुतिकरण' },
  { en: 'Subscription', ne: 'सदस्यता' },
  { en: 'Sustainability', ne: 'दिगोपन' },
  { en: 'Symbolism', ne: 'प्रतीकवाद' },
  { en: 'Synchronization', ne: 'समकालिकरण' },
  { en: 'Systematic', ne: 'व्यवस्थित' },
  { en: 'Transparency', ne: 'पारदर्शिता' },
  { en: 'Transportation', ne: 'यातायात' },
  { en: 'Treatment', ne: 'उपचार' },
  { en: 'Unification', ne: 'एककरण' },
  { en: 'Utilization', ne: 'उपयोग' },
  { en: 'Validation', ne: 'प्रमाणीकरण' },
  { en: 'Verification', ne: 'पुष्टि' },
  { en: 'Violation', ne: 'उल्लङ्घन' },
  { en: 'Visualization', ne: 'दृश्य कल्पना' },
  { en: 'Worship', ne: 'पूजा' },
  { en: 'Worldwide', ne: 'विश्वव्यापी' },
  { en: 'Worthiness', ne: 'योग्यपन' },
  { en: 'Affiliation', ne: 'सम्बन्ध' },
  { en: 'Authorization', ne: 'अधिकार प्रदान' },
  { en: 'Categorization', ne: 'वर्गीकरण' },
  { en: 'Corruption', ne: 'भ्रष्टाचार' },
  { en: 'Creation', ne: 'सिर्जना' },
  { en: 'Credibility', ne: 'विश्वसनीयता' },
  { en: 'Occasion', ne: 'अवसर' },
  { en: 'Discrimination', ne: 'भेदभाव' },
  { en: 'Environmental', ne: 'वातावरणीय' },
  { en: 'Estimation', ne: 'अनुमान' },
  { en: 'Experimentation', ne: 'प्रयोग' },
  { en: 'Facilitation', ne: 'सहजीकरण' },
  { en: 'Familiarization', ne: 'परिचित गराउने प्रक्रिया' },
  { en: 'Fertilization', ne: 'उर्वरीकरण' },
  { en: 'Fragmentation', ne: 'टुक्रिनु' },
  { en: 'Functionality', ne: 'कार्यक्षमता' },
  { en: 'Globalization', ne: 'विश्वव्यापीकरण' },
  { en: 'Gratification', ne: 'सन्तुष्टि' },
  { en: 'Identification', ne: 'पहिचान' },
  { en: 'Incorporation', ne: 'समावेश' },
  { en: 'Indication', ne: 'संकेत' },
  { en: 'Industrialization', ne: 'औद्योगिकीकरण' },
  { en: 'Inequality', ne: 'असमानता' },
  { en: 'Inflammation', ne: 'सुजन' },
  { en: 'Infrastructure', ne: 'पूर्वाधार' },
  { en: 'Isolation', ne: 'एकान्तता' },
  { en: 'Justification', ne: 'औचित्य' },
  { en: 'Legislation', ne: 'कानून निर्माण' },
  { en: 'Liberation', ne: 'मुक्ति' },
  { en: 'Manipulation', ne: 'हेरफेर' },
  { en: 'Modernization', ne: 'आधुनिकीकरण' },
  { en: 'Probability', ne: 'सम्भावना' },
  { en: 'Progression', ne: 'प्रगति' },
  { en: 'Remuneration', ne: 'पारिश्रमिक' },
  { en: 'Strengthening', ne: 'सुदृढीकरण' },
  { en: 'Approximation', ne: 'अनुमान' },
  { en: 'Collaboration', ne: 'सहकार्य' },
  { en: 'Communication', ne: 'सञ्चार' },
  { en: 'Compilation', ne: 'संकलन' },
  { en: 'Composition', ne: 'संरचना' },
  { en: 'Concentration', ne: 'ध्यान' },
  { en: 'Configuration', ne: 'संरचना' },
  { en: 'Confrontation', ne: 'सामना' },
  { en: 'Consciousness', ne: 'चेतना' },
  { en: 'Consolidation', ne: 'सुदृढीकरण' },
  { en: 'Consultation', ne: 'परामर्श' },
  { en: 'Contamination', ne: 'प्रदूषण' },
  { en: 'Contribution', ne: 'योगदान' },
  { en: 'Coordination', ne: 'समन्वय' },
  { en: 'Creativity', ne: 'सिर्जनशीलता' },
  { en: 'Cultivation', ne: 'खेती' },
  { en: 'Declaration', ne: 'घोषणा' },
  { en: 'Dedication', ne: 'समर्पण' },
  { en: 'Definition', ne: 'परिभाषा' },
  { en: 'Delegation', ne: 'प्रतिनिधिमण्डल' },
  { en: 'Determination', ne: 'दृढता' },
  { en: 'Developmental', ne: 'विकासात्मक' },
  { en: 'Differentiation', ne: 'भिन्नता' },
  { en: 'Distribution', ne: 'वितरण' },
  { en: 'Documentation', ne: 'दस्तावेजीकरण' },
  { en: 'Domination', ne: 'प्रभुत्व' },
  { en: 'Educationist', ne: 'शिक्षाविद्' },
  { en: 'Effectiveness', ne: 'प्रभावकारिता' },
  { en: 'Eligibility', ne: 'योग्यता' },
  { en: 'Empowerment', ne: 'सशक्तिकरण' },
  { en: 'Enforcement', ne: 'कार्यान्वयन' },
  { en: 'Enlightenment', ne: 'ज्ञानप्राप्ति' },
  { en: 'Enhancement', ne: 'सुधार' },
  { en: 'Talk', ne: 'कुरा गर्नु' },
  { en: 'Teach', ne: 'सिकाउनु' },
  { en: 'Tell', ne: 'भन्नु' },
  { en: 'Tend', ne: 'झुकाव हुनु' },
  { en: 'Test', ne: 'परीक्षण गर्नु' },
  { en: 'Thank', ne: 'धन्यवाद दिनु' },
  { en: 'Think', ne: 'सोत्नु' },
  { en: 'Throw', ne: 'फ्याँक्नु' },
  { en: 'Touch', ne: 'छोउनु' },
  { en: 'Train', ne: 'तालिम दिनु' },
  { en: 'Travel', ne: 'यात्रा गर्नु' },
  { en: 'Try', ne: 'प्रयास गर्नु' },
  { en: 'Turn', ne: 'घुमाउनु' },
];

export const academicVocabulary = [
  { en: 'Barrier', ne: 'अवरोध' },
  { en: 'Behavior', ne: 'व्यवहार' },
  { en: 'Biology', ne: 'जीवविज्ञान' },
  { en: 'Capable', ne: 'सक्षम' },
  { en: 'Capacity', ne: 'क्षमता' },
  { en: 'Cautious', ne: 'सतर्क' },
  { en: 'Celebrate', ne: 'मनाउनु' },
  { en: 'Channel', ne: 'माध्यम' },
  { en: 'Chaos', ne: 'अव्यवस्था' },
  { en: 'Charity', ne: 'दान' },
  { en: 'Chemical', ne: 'रसायन' },
  { en: 'Commitment', ne: 'प्रतिबद्धता' },
  { en: 'Community', ne: 'समुदाय' },
  { en: 'Confusion', ne: 'अन्योल' },
  { en: 'Conscious', ne: 'सचेत' },
  { en: 'Consequence', ne: 'परिणाम' },
  { en: 'Convenient', ne: 'सहज' },
  { en: 'Conversation', ne: 'कुराकानी' },
  { en: 'Corrupt', ne: 'भ्रष्ट' },
  { en: 'Creation', ne: 'सिर्जना' },
  { en: 'Creative', ne: 'सिर्जनशील' },
  { en: 'Crisis', ne: 'संकट' },
  { en: 'Decision', ne: 'निर्णय' },
  { en: 'Democracy', ne: 'लोकतन्त्र' },
  { en: 'Dependent', ne: 'आश्रित' },
  { en: 'Detail', ne: 'विवरण' },
  { en: 'Device', ne: 'उपकरण' },
  { en: 'Diagnose', ne: 'पहिचान गर्नु' },
  { en: 'Difference', ne: 'भिन्नता' },
  { en: 'Difficulty', ne: 'कठिनाइ' },
  { en: 'Dimension', ne: 'आयाम' },
  { en: 'Disaster', ne: 'विपत्ति' },
  { en: 'Discipline', ne: 'अनुशासन' },
  { en: 'Disease', ne: 'रोग' },
  { en: 'Distance', ne: 'दूरी' },
  { en: 'Economy', ne: 'अर्थतन्त्र' },
  { en: 'Effect', ne: 'प्रभाव' },
  { en: 'Effort', ne: 'प्रयास' },
  { en: 'Element', ne: 'तत्व' },
  { en: 'Emotion', ne: 'भावना' },
  { en: 'Emphasize', ne: 'जोड दिनु' },
  { en: 'Enable', ne: 'सक्षम बनाउनु' },
  { en: 'Encounter', ne: 'सामना गर्नु' },
  { en: 'Energy', ne: 'ऊर्जा' },
  { en: 'Engage', ne: 'संलग्न हुनु' },
  { en: 'Environment', ne: 'वातावरण' },
  { en: 'Evidence', ne: 'प्रमाण' },
  { en: 'Evolve', ne: 'विकास हुनु' },
  { en: 'Example', ne: 'उदाहरण' },
  { en: 'Expert', ne: 'विशेषज्ञ' },
  { en: 'External', ne: 'बाह्य' },
  { en: 'Factor', ne: 'तत्व' },
  { en: 'Failure', ne: 'असफलता' },
  { en: 'Feature', ne: 'विशेषता' },
  { en: 'Finance', ne: 'वित्त' },
  { en: 'Foreign', ne: 'विदेशी' },
  { en: 'Formula', ne: 'सूत्र' },
  { en: 'Foundation', ne: 'आधार' },
  { en: 'Fraction', ne: 'अंश' },
  { en: 'Function', ne: 'कार्य' },
  { en: 'Global', ne: 'विश्वव्यापी' },
  { en: 'Government', ne: 'सरकार' },
  { en: 'Guarantee', ne: 'ग्यारेन्टी' },
  { en: 'Guidance', ne: 'मार्गदर्शन' },
  { en: 'Habit', ne: 'बानी' },
  { en: 'Harmony', ne: 'सद्भाव' },
  { en: 'Hazard', ne: 'खतरा' },
  { en: 'Impact', ne: 'प्रभाव' },
  { en: 'Imply', ne: 'संकेत गर्नु' },
  { en: 'Individual', ne: 'व्यक्तिगत' },
  { en: 'Industry', ne: 'उद्योग' },
  { en: 'Initial', ne: 'प्रारम्भिक' },
  { en: 'Input', ne: 'इनपुट' },
  { en: 'Insert', ne: 'राख्नु' },
  { en: 'Institute', ne: 'संस्था' },
  { en: 'Intelligence', ne: 'बुद्धिमत्ता' },
  { en: 'Interaction', ne: 'अन्तरक्रिया' },
  { en: 'Interest', ne: 'रुचि' },
  { en: 'Intervene', ne: 'हस्तक्षेप गर्नु' },
  { en: 'Knowledge', ne: 'ज्ञान' },
  { en: 'Label', ne: 'नाम दिनु' },
  { en: 'Labor', ne: 'श्रम' },
  { en: 'Legal', ne: 'कानुनी' },
  { en: 'Liberal', ne: 'उदार' },
  { en: 'Logic', ne: 'तर्क' },
  { en: 'Major', ne: 'प्रमुख' },
  { en: 'Manipulate', ne: 'हेरफेर गर्नु' },
  { en: 'Manufacture', ne: 'उत्पादन गर्नु' },
  { en: 'Margin', ne: 'किनारा' },
  { en: 'Material', ne: 'सामग्री' },
  { en: 'Mechanism', ne: 'संयन्त्र' },
  { en: 'Media', ne: 'सञ्चार माध्यम' },
  { en: 'Motive', ne: 'उद्देश्य' },
  { en: 'Network', ne: 'सञ्जाल' },
  { en: 'Notion', ne: 'धारणा' },
  { en: 'Obvious', ne: 'स्पष्ट' },
  { en: 'Occur', ne: 'घट्नु / हुनु' },
  { en: 'Opportunity', ne: 'अवसर' },
  { en: 'Oppose', ne: 'विरोध गर्नु' },
  { en: 'Option', ne: 'विकल्प' },
  { en: 'Outcome', ne: 'परिणाम' },
  { en: 'Perceive', ne: 'बुझ्नु' },
  { en: 'Persist', ne: 'निरन्तर रहनु' },
  { en: 'Perspective', ne: 'दृष्टिकोण' },
  { en: 'Phase', ne: 'चरण' },
  { en: 'Phenomenon', ne: 'घटना' },
  { en: 'Policy', ne: 'नीति' },
  { en: 'Potential', ne: 'सम्भावना' },
  { en: 'Precise', ne: 'सटीक' },
  { en: 'Predict', ne: 'भविष्यवाणी गर्नु' },
  { en: 'Principle', ne: 'सिद्धान्त' },
  { en: 'Priority', ne: 'प्राथमिकता' },
  { en: 'Proceed', ne: 'अगाडि बढ्नु' },
  { en: 'Propose', ne: 'प्रस्ताव गर्नु' },
  { en: 'Prospect', ne: 'सम्भावना' },
  { en: 'Quality', ne: 'गुणस्तर' },
  { en: 'Quantity', ne: 'मात्रा' },
  { en: 'Recall', ne: 'सम्झनु' },
  { en: 'Recruit', ne: 'भर्ती गर्नु' },
  { en: 'Reform', ne: 'सुधार गर्नु' },
  { en: 'Relevant', ne: 'सम्बन्धित' },
  { en: 'Reserve', ne: 'आरक्षित गर्नु' },
  { en: 'Reverse', ne: 'उल्टाउनु' },
  { en: 'Revolution', ne: 'क्रान्ति' },
  { en: 'Role', ne: 'भूमिका' },
  { en: 'Seek', ne: 'खोज्नु' },
  { en: 'Sense', ne: 'भावना / अर्थ' },
  { en: 'Sequence', ne: 'क्रम' },
  { en: 'Significant', ne: 'महत्वपूर्ण' },
  { en: 'Similar', ne: 'समान' },
  { en: 'Source', ne: 'स्रोत' },
  { en: 'Specific', ne: 'विशेष' },
  { en: 'Structure', ne: 'संरचना' },
  { en: 'Substitute', ne: 'सट्टा' },
  { en: 'Summarize', ne: 'सारांश गर्नु' },
  { en: 'Survey', ne: 'सर्वेक्षण' },
  { en: 'System', ne: 'प्रणाली' },
  { en: 'Technique', ne: 'प्रविधि' },
  { en: 'Technology', ne: 'प्रविधि' },
  { en: 'Theory', ne: 'सिद्धान्त' },
  { en: 'Trend', ne: 'प्रवृत्ति' },
  { en: 'Trigger', ne: 'सुरु गराउनु' },
  { en: 'Ultimate', ne: 'अन्तिम' },
  { en: 'Unique', ne: 'अद्वितीय' },
  { en: 'Valid', ne: 'मान्य' },
  { en: 'Value', ne: 'मूल्य' },
  { en: 'Variable', ne: 'परिवर्तनशील' },
  { en: 'Version', ne: 'संस्करण' },
  { en: 'Virtual', ne: 'आभासी' },
  { en: 'Visible', ne: 'देखिने' },
  { en: 'Volume', ne: 'आयतन' },
  { en: 'Vulnerable', ne: 'कमजोर' },
  { en: 'Welfare', ne: 'कल्याण' },
  { en: 'Witness', ne: 'साक्षी' },
  { en: 'Workshop', ne: 'कार्यशाला' },
  { en: 'World', ne: 'संसार' },
  { en: 'Worth', ne: 'मूल्य' },
  { en: 'Zone', ne: 'क्षेत्र' },
  { en: 'Accumulate', ne: 'जम्मा गर्नु' },
  { en: 'Appropriate', ne: 'उपयुक्त' },
  { en: 'Approximate', ne: 'करिब' },
  { en: 'Arbitrary', ne: 'मनपरी' },
  { en: 'Attain', ne: 'हासिल गर्नु' },
  { en: 'Attribute', ne: 'सम्बन्धित गर्नु' },
  { en: 'Aware', ne: 'सचेत' },
  { en: 'Bias', ne: 'पक्षपात' },
  { en: 'Category', ne: 'वर्ग' },
  { en: 'Circumstance', ne: 'परिस्थिति' },
  { en: 'Collaborate', ne: 'सहकार्य गर्नु' },
  { en: 'Commence', ne: 'सुरु गर्नु' },
  { en: 'Compensate', ne: 'क्षतिपूर्ति दिनु' },
  { en: 'Competent', ne: 'सक्षम' },
  { en: 'Comply', ne: 'पालन गर्नु' },
  { en: 'Conceal', ne: 'लुकाउनु' },
  { en: 'Considerable', ne: 'महत्वपूर्ण' },
  { en: 'Consistent', ne: 'निरन्तर' },
  { en: 'Constitute', ne: 'गठन गर्नु' },
  { en: 'Constrain', ne: 'सीमित गर्नु' },
  { en: 'Consult', ne: 'परामर्श लिनु' },
  { en: 'Contemplate', ne: 'विचार गर्नु' },
  { en: 'Contradict', ne: 'विरोध गर्नु' },
  { en: 'Crucial', ne: 'अत्यन्त महत्वपूर्ण' },
  { en: 'Cultivate', ne: 'विकास गर्नु' },
  { en: 'Derive', ne: 'निकाल्नु' },
  { en: 'Designate', ne: 'तोक्नु' },
  { en: 'Detect', ne: 'पत्ता लगाउनु' },
  { en: 'Devise', ne: 'योजना बनाउनु' },
  { en: 'Diminish', ne: 'घटाउनु' },
  { en: 'Discriminate', ne: 'भेदभाव गर्नु' },
  { en: 'Emerge', ne: 'देखा पर्नु' },
  { en: 'Collapse', ne: 'ढल्नु' },
  { en: 'Colleague', ne: 'सहकर्मी' },
  { en: 'Combination', ne: 'संयोजन' },
  { en: 'Comfort', ne: 'आराम' },
  { en: 'Command', ne: 'आदेश' },
  { en: 'Comment', ne: 'टिप्पणी' },
  { en: 'Commit', ne: 'प्रतिबद्ध हुनु' },
  { en: 'Communicate', ne: 'सञ्चार गर्नु' },
  { en: 'Compare', ne: 'तुलना गर्नु' },
  { en: 'Compete', ne: 'प्रतिस्पर्धा गर्नु' },
  { en: 'Compile', ne: 'सङ्कलन गर्नु' },
  { en: 'Complete', ne: 'पूरा गर्नु' },
  { en: 'Complex', ne: 'जटिल' },
  { en: 'Compose', ne: 'रचना गर्नु' },
  { en: 'Comprehend', ne: 'बुझ्नु' },
  { en: 'Concentrate', ne: 'ध्यान दिनु' },
  { en: 'Concept', ne: 'अवधारणा' },
  { en: 'Concern', ne: 'चिन्ता' },
  { en: 'Conclude', ne: 'निष्कर्ष निकाल्नु' },
  { en: 'Condition', ne: 'अवस्था' },
  { en: 'Conduct', ne: 'सञ्चालन गर्नु' },
  { en: 'Confirm', ne: 'पुष्टि गर्नु' },
  { en: 'Conflict', ne: 'द्वन्द्व' },
  { en: 'Confuse', ne: 'अलमल पार्नु' },
  { en: 'Connect', ne: 'जोड्नु' },
  { en: 'Consider', ne: 'विचार गर्नु' },
  { en: 'Consist', ne: 'समावेश हुनु' },
  { en: 'Constant', ne: 'स्थिर' },
  { en: 'Construct', ne: 'निर्माण गर्नु' },
  { en: 'Consume', ne: 'उपभोग गर्नु' },
  { en: 'Contact', ne: 'सम्पर्क' },
  { en: 'Contain', ne: 'समेट्नु' },
  { en: 'Context', ne: 'सन्दर्भ' },
  { en: 'Continue', ne: 'जारी राख्नु' },
  { en: 'Contrast', ne: 'भिन्नता' },
  { en: 'Contribute', ne: 'योगदान गर्नु' },
  { en: 'Control', ne: 'नियन्त्रण' },
  { en: 'Convert', ne: 'परिवर्तन गर्नु' },
  { en: 'Convince', ne: 'विश्वस्त पार्नु' },
  { en: 'Cooperate', ne: 'सहकार्य गर्नु' },
  { en: 'Coordinate', ne: 'समन्वय गर्नु' },
  { en: 'Correct', ne: 'सही बनाउनु' },
  { en: 'Correspond', ne: 'मेल खानु' },
  { en: 'Create', ne: 'सिर्जना गर्नु' },
  { en: 'Credit', ne: 'श्रेय' },
  { en: 'Criticize', ne: 'आलोचना गर्नु' },
  { en: 'Culture', ne: 'संस्कृति' },
  { en: 'Damage', ne: 'क्षति' },
  { en: 'Debate', ne: 'बहस' },
  { en: 'Decide', ne: 'निर्णय गर्नु' },
  { en: 'Declare', ne: 'घोषणा गर्नु' },
  { en: 'Decline', ne: 'घट्नु' },
  { en: 'Decrease', ne: 'कम हुनु' },
  { en: 'Dedicate', ne: 'समर्पण गर्नु' },
  { en: 'Define', ne: 'परिभाषा गर्नु' },
  { en: 'Delay', ne: 'ढिलाइ गर्नु' },
  { en: 'Deliver', ne: 'पुर्याउनु' },
  { en: 'Demand', ne: 'माग' },
  { en: 'Demonstrate', ne: 'देखाउनु' },
  { en: 'Deny', ne: 'अस्वीकार गर्नु' },
  { en: 'Depend', ne: 'भर पर्नु' },
  { en: 'Describe', ne: 'वर्णन गर्नु' },
  { en: 'Design', ne: 'डिजाइन गर्नु' },
  { en: 'Desire', ne: 'इच्छा' },
  { en: 'Destroy', ne: 'नष्ट गर्नु' },
  { en: 'Determine', ne: 'निर्धारण गर्नु' },
  { en: 'Develop', ne: 'विकास गर्नु' },
  { en: 'Differ', ne: 'फरक हुनु' },
  { en: 'Difficult', ne: 'कठिन' },
  { en: 'Direct', ne: 'सीधा' },
  { en: 'Discover', ne: 'पत्ता लगाउनु' },
  { en: 'Discuss', ne: 'छलफल गर्नु' },
  { en: 'Display', ne: 'प्रदर्शन गर्नु' },
  { en: 'Distribute', ne: 'वितरण गर्नु' },
  { en: 'Divide', ne: 'विभाजन गर्नु' },
  { en: 'Document', ne: 'कागजात' },
  { en: 'Dominate', ne: 'प्रभुत्व जमाउनु' },
  { en: 'Doubt', ne: 'शंका' },
  { en: 'Download', ne: 'डाउनलोड गर्नु' },
  { en: 'Drag', ne: 'तान्नु' },
  { en: 'Draw', ne: 'कोर्नु' },
  { en: 'Dream', ne: 'सपना' },
  { en: 'Drive', ne: 'चलाउनु' },
  { en: 'Drop', ne: 'झार्नु' },
  { en: 'Earn', ne: 'कमाउनु' },
  { en: 'Edit', ne: 'सम्पादन गर्नु' },
  { en: 'Educate', ne: 'शिक्षा दिनु' },
  { en: 'Eliminate', ne: 'हटाउनु' },
  { en: 'Employ', ne: 'रोजगारी दिनु' },
  { en: 'Encourage', ne: 'प्रोत्साहन गर्नु' },
  { en: 'End', ne: 'समाप्त गर्नु' },
  { en: 'Enhance', ne: 'सुधार गर्नु' },
  { en: 'Enjoy', ne: 'आनन्द लिनु' },
  { en: 'Ensure', ne: 'सुनिश्चित गर्नु' },
  { en: 'Enter', ne: 'प्रवेश गर्नु' },
  { en: 'Establish', ne: 'स्थापना गर्नु' },
  { en: 'Estimate', ne: 'अनुमान गर्नु' },
  { en: 'Evaluate', ne: 'मूल्याङ्कन गर्नु' },
  { en: 'Examine', ne: 'जाँच गर्नु' },
  { en: 'Exceed', ne: 'नाघ्नु' },
  { en: 'Abandon', ne: 'त्याग्नु' },
  { en: 'Ability', ne: 'क्षमता' },
  { en: 'Abnormal', ne: 'असामान्य' },
  { en: 'Abolish', ne: 'हटाउनु' },
  { en: 'Absorb', ne: 'सोस्नु' },
  { en: 'Abstract', ne: 'अमूर्त' },
  { en: 'Abuse', ne: 'दुरुपयोग' },
  { en: 'Accelerate', ne: 'तीव्र बनाउनु' },
  { en: 'Access', ne: 'पहुँच' },
  { en: 'Accommodate', ne: 'मिलाउनु' },
  { en: 'Accompany', ne: 'साथ दिनु' },
  { en: 'Accomplish', ne: 'पूरा गर्नु' },
  { en: 'Account', ne: 'खाता' },
  { en: 'Accurate', ne: 'सही' },
  { en: 'Accuse', ne: 'आरोप लगाउनु' },
  { en: 'Achieve', ne: 'हासिल गर्नु' },
  { en: 'Acknowledge', ne: 'स्वीकार गर्नु' },
  { en: 'Acquire', ne: 'प्राप्त गर्नु' },
  { en: 'Adapt', ne: 'अनुकूलन गर्नु' },
  { en: 'Adequate', ne: 'पर्याप्त' },
  { en: 'Adjust', ne: 'मिलाउनु' },
  { en: 'Administer', ne: 'सञ्चालन गर्नु' },
  { en: 'Admire', ne: 'प्रशंसा गर्नु' },
  { en: 'Admit', ne: 'स्वीकार गर्नु' },
  { en: 'Adopt', ne: 'अपनाउनु' },
  { en: 'Advance', ne: 'अगाडि बढ्नु' },
  { en: 'Advantage', ne: 'फाइदा' },
  { en: 'Advertise', ne: 'विज्ञापन गर्नु' },
  { en: 'Advocate', ne: 'समर्थन गर्नु' },
  { en: 'Affect', ne: 'प्रभाव पार्नु' },
  { en: 'Afford', ne: 'खर्च गर्न सक्नु' },
  { en: 'Agency', ne: 'संस्था' },
  { en: 'Agenda', ne: 'कार्यसूची' },
  { en: 'Aggressive', ne: 'आक्रामक' },
  { en: 'Agreement', ne: 'सम्झौता' },
  { en: 'Agriculture', ne: 'कृषि' },
  { en: 'Aid', ne: 'सहयोग' },
  { en: 'Aim', ne: 'लक्ष्य' },
  { en: 'Alarm', ne: 'चेतावनी' },
  { en: 'Alert', ne: 'सचेत' },
  { en: 'Allocate', ne: 'बाँडफाँड गर्नु' },
  { en: 'Alter', ne: 'परिवर्तन गर्नु' },
  { en: 'Analyze', ne: 'विश्लेषण गर्नु' },
  { en: 'Announce', ne: 'घोषणा गर्नु' },
  { en: 'Anticipate', ne: 'अपेक्षा गर्नु' },
  { en: 'Anxiety', ne: 'चिन्ता' },
  { en: 'Apologize', ne: 'माफी माग्नु' },
  { en: 'Appear', ne: 'देखा पर्नु' },
  { en: 'Apply', ne: 'लागू गर्नु' },
  { en: 'Appreciate', ne: 'कदर गर्नु' },
  { en: 'Approach', ne: 'नजिक जानु' },
  { en: 'Approve', ne: 'स्वीकृत गर्नु' },
  { en: 'Argue', ne: 'तर्क गर्नु' },
  { en: 'Arise', ne: 'उत्पन्न हुनु' },
  { en: 'Arrange', ne: 'मिलाउनु' },
  { en: 'Arrest', ne: 'पक्राउ गर्नु' },
  { en: 'Arrive', ne: 'पुग्नु' },
  { en: 'Assess', ne: 'मूल्याङ्कन गर्नु' },
  { en: 'Assign', ne: 'जिम्मा दिनु' },
  { en: 'Assist', ne: 'सहयोग गर्नु' },
  { en: 'Assume', ne: 'मान्नु' },
  { en: 'Assure', ne: 'विश्वास दिलाउनु' },
  { en: 'Attach', ne: 'जोड्नु' },
  { en: 'Attempt', ne: 'प्रयास' },
  { en: 'Attend', ne: 'उपस्थित हुनु' },
  { en: 'Attract', ne: 'आकर्षित गर्नु' },
  { en: 'Avoid', ne: 'बच्नु' },
  { en: 'Award', ne: 'पुरस्कार' },
  { en: 'Balance', ne: 'सन्तुलन' },
  { en: 'Ban', ne: 'प्रतिबन्ध' },
  { en: 'Base', ne: 'आधार' },
  { en: 'Behave', ne: 'व्यवहार गर्नु' },
  { en: 'Benefit', ne: 'फाइदा' },
  { en: 'Blame', ne: 'दोष दिनु' },
  { en: 'Bond', ne: 'सम्बन्ध' },
  { en: 'Boost', ne: 'बढाउनु' },
  { en: 'Border', ne: 'सिमाना' },
  { en: 'Bother', ne: 'झन्झट दिनु' },
  { en: 'Budget', ne: 'बजेट' },
  { en: 'Build', ne: 'निर्माण गर्नु' },
  { en: 'Burden', ne: 'बोझ' },
  { en: 'Calculate', ne: 'गणना गर्नु' },
  { en: 'Capture', ne: 'समात्नु' },
  { en: 'Career', ne: 'करियर' },
  { en: 'Carry', ne: 'बोक्नु' },
  { en: 'Cease', ne: 'रोक्नु' },
  { en: 'Challenge', ne: 'चुनौती' },
  { en: 'Change', ne: 'परिवर्तन' },
  { en: 'Clarify', ne: 'स्पष्ट गर्नु' },
  { en: 'Classify', ne: 'वर्गीकरण गर्नु' },
  { en: 'Combine', ne: 'मिलाउनु' },
  { en: 'Exchange', ne: 'साटासाट' },
  { en: 'Excite', ne: 'उत्साहित गर्नु' },
  { en: 'Exclude', ne: 'बाहिर राख्नु' },
  { en: 'Execute', ne: 'कार्यान्वयन गर्नु' },
  { en: 'Exercise', ne: 'अभ्यास' },
  { en: 'Exhibit', ne: 'प्रदर्शन गर्नु' },
  { en: 'Expand', ne: 'विस्तार गर्नु' },
  { en: 'Expect', ne: 'अपेक्षा गर्नु' },
  { en: 'Experience', ne: 'अनुभव' },
  { en: 'Experiment', ne: 'प्रयोग' },
  { en: 'Explain', ne: 'व्याख्या गर्नु' },
  { en: 'Explore', ne: 'अन्वेषण गर्नु' },
  { en: 'Expose', ne: 'उजागर गर्नु' },
  { en: 'Express', ne: 'व्यक्त गर्नु' },
  { en: 'Extend', ne: 'विस्तार गर्नु' },
  { en: 'Extract', ne: 'निकाल्नु' },
  { en: 'Facilitate', ne: 'सहज बनाउनु' },
  { en: 'Fail', ne: 'असफल हुनु' },
  { en: 'Focus', ne: 'ध्यान दिनु' },
  { en: 'Force', ne: 'शक्ति' },
  { en: 'Forecast', ne: 'पूर्वानुमान' },
  { en: 'Forget', ne: 'बिर्सनु' },
  { en: 'Form', ne: 'गठन गर्नु' },
  { en: 'Formulate', ne: 'बनाउनु' },
  { en: 'Foster', ne: 'विकास गर्नु' },
  { en: 'Gain', ne: 'प्राप्त गर्नु' },
  { en: 'Generate', ne: 'उत्पादन गर्नु' },
  { en: 'Govern', ne: 'शासन गर्नु' },
  { en: 'Guide', ne: 'मार्गदर्शन गर्नु' },
  { en: 'Handle', ne: 'सम्हाल्नु' },
  { en: 'Happen', ne: 'हुनु' },
  { en: 'Harm', ne: 'हानि गर्नु' },
  { en: 'Hate', ne: 'घृणा गर्नु' },
  { en: 'Heal', ne: 'निको पार्नु' },
  { en: 'Help', ne: 'सहयोग गर्नु' },
  { en: 'Highlight', ne: 'मुख्य बनाउनु' },
  { en: 'Identify', ne: 'पहिचान गर्नु' },
  { en: 'Ignore', ne: 'बेवास्ता गर्नु' },
  { en: 'Illustrate', ne: 'उदाहरण दिनु' },
  { en: 'Imagine', ne: 'कल्पना गर्नु' },
  { en: 'Implement', ne: 'लागू गर्नु' },
  { en: 'Improve', ne: 'सुधार गर्नु' },
  { en: 'Include', ne: 'समावेश गर्नु' },
  { en: 'Increase', ne: 'बढाउनु' },
  { en: 'Indicate', ne: 'संकेत गर्नु' },
  { en: 'Influence', ne: 'प्रभाव पार्नु' },
  { en: 'Inform', ne: 'जानकारी दिनु' },
  { en: 'Initiate', ne: 'सुरु गर्नु' },
  { en: 'Innovate', ne: 'नयाँ बनाउनु' },
  { en: 'Inspect', ne: 'जाँच गर्नु' },
  { en: 'Inspire', ne: 'प्रेरित गर्नु' },
  { en: 'Install', ne: 'स्थापना गर्नु' },
  { en: 'Integrate', ne: 'एकीकृत गर्नु' },
  { en: 'Interact', ne: 'अन्तरक्रिया गर्नु' },
  { en: 'Interpret', ne: 'व्याख्या गर्नु' },
  { en: 'Introduce', ne: 'परिचय गराउनु' },
  { en: 'Investigate', ne: 'अनुसन्धान गर्नु' },
  { en: 'Involve', ne: 'संलग्न गर्नु' },
  { en: 'Isolate', ne: 'अलग गर्नु' },
  { en: 'Issue', ne: 'समस्या' },
  { en: 'Join', ne: 'जोडिनु' },
  { en: 'Judge', ne: 'निर्णय गर्नु' },
  { en: 'Justify', ne: 'औचित्य दिनु' },
  { en: 'Keep', ne: 'राख्नु' },
  { en: 'Know', ne: 'जान्नु' },
  { en: 'Lack', ne: 'अभाव हुनु' },
  { en: 'Launch', ne: 'सुरु गर्नु' },
  { en: 'Lead', ne: 'नेतृत्व गर्नु' },
  { en: 'Learn', ne: 'सिक्नु' },
  { en: 'Leave', ne: 'छोड्नु' },
  { en: 'Limit', ne: 'सीमित गर्नु' },
  { en: 'Link', ne: 'जोड्नु' },
  { en: 'Locate', ne: 'पत्ता लगाउनु' },
  { en: 'Maintain', ne: 'कायम राख्नु' },
  { en: 'Manage', ne: 'व्यवस्थापन गर्नु' },
  { en: 'Measure', ne: 'मापन गर्नु' },
  { en: 'Mention', ne: 'उल्लेख गर्नु' },
  { en: 'Modify', ne: 'परिवर्तन गर्नु' },
  { en: 'Monitor', ne: 'निगरानी गर्नु' },
  { en: 'Motivate', ne: 'प्रेरित गर्नु' },
  { en: 'Move', ne: 'सार्नु' },
  { en: 'Notice', ne: 'ध्यान दिनु' },
  { en: 'Observe', ne: 'अवलोकन गर्नु' },
  { en: 'Obtain', ne: 'प्राप्त गर्नु' },
  { en: 'Operate', ne: 'सञ्चालन गर्नु' },
  { en: 'Organize', ne: 'व्यवस्थित गर्नु' },
  { en: 'Overcome', ne: 'जित्नु' },
  { en: 'Participate', ne: 'सहभागिता जनाउनु' },
  { en: 'Perform', ne: 'प्रदर्शन गर्नु' },
  { en: 'Persuade', ne: 'मनाउनु' },
  { en: 'Plan', ne: 'योजना बनाउनु' },
  { en: 'Prepare', ne: 'तयारी गर्नु' },
  { en: 'Present', ne: 'प्रस्तुत गर्नु' },
  { en: 'Preserve', ne: 'संरक्षण गर्नु' },
  { en: 'Prevent', ne: 'रोक्नु' },
  { en: 'Process', ne: 'प्रक्रिया' },
  { en: 'Produce', ne: 'उत्पादन गर्नु' },
  { en: 'Promote', ne: 'प्रवर्द्धन गर्नु' },
  { en: 'Protect', ne: 'सुरक्षा गर्नु' },
  { en: 'Prove', ne: 'प्रमाणित गर्नु' },
  { en: 'Provide', ne: 'उपलब्ध गराउनु' },
  { en: 'Publish', ne: 'प्रकाशन गर्नु' },
  { en: 'Pursue', ne: 'पछ्याउनु' },
  { en: 'Qualify', ne: 'योग्य हुनु' },
  { en: 'Question', ne: 'प्रश्न' },
  { en: 'Quit', ne: 'छोड्नु' },
  { en: 'Raise', ne: 'उठाउनु' },
  { en: 'Reach', ne: 'पुग्नु' },
  { en: 'React', ne: 'प्रतिक्रिया दिनु' },
  { en: 'Read', ne: 'पढ्नु' },
  { en: 'Realize', ne: 'महसुस गर्नु' },
  { en: 'Receive', ne: 'प्राप्त गर्नु' },
  { en: 'Recognize', ne: 'पहिचान गर्नु' },
  { en: 'Recommend', ne: 'सिफारिस गर्नु' },
  { en: 'Recover', ne: 'पुनःप्राप्त गर्नु' },
  { en: 'Reduce', ne: 'घटाउनु' },
  { en: 'Refer', ne: 'उल्लेख गर्नु' },
  { en: 'Reflect', ne: 'प्रतिबिम्बित गर्नु' },
  { en: 'Refuse', ne: 'अस्वीकार गर्नु' },
  { en: 'Regard', ne: 'मान्नु' },
  { en: 'Regulate', ne: 'नियन्त्रण गर्नु' },
  { en: 'Reinforce', ne: 'सुदृढ गर्नु' },
  { en: 'Reject', ne: 'अस्वीकार गर्नु' },
  { en: 'Relate', ne: 'सम्बन्ध राख्नु' },
  { en: 'Release', ne: 'छोड्नु' },
  { en: 'Rely', ne: 'भर पर्नु' },
  { en: 'Remain', ne: 'बाँकी रहनु' },
  { en: 'Remember', ne: 'सम्झनु' },
  { en: 'Remove', ne: 'हटाउनु' },
  { en: 'Repair', ne: 'मर्मत गर्नु' },
  { en: 'Repeat', ne: 'दोहोर्याउनु' },
  { en: 'Replace', ne: 'प्रतिस्थापन गर्नु' },
  { en: 'Reply', ne: 'जवाफ दिनु' },
  { en: 'Report', ne: 'प्रतिवेदन' },
  { en: 'Represent', ne: 'प्रतिनिधित्व गर्नु' },
  { en: 'Require', ne: 'आवश्यकता हुनु' },
  { en: 'Research', ne: 'अनुसन्धान गर्नु' },
  { en: 'Resist', ne: 'प्रतिरोध गर्नु' },
  { en: 'Resolve', ne: 'समाधान गर्नु' },
  { en: 'Respond', ne: 'प्रतिक्रिया दिनु' },
  { en: 'Restore', ne: 'पुनःस्थापना गर्नु' },
  { en: 'Restrict', ne: 'सीमित गर्नु' },
  { en: 'Result', ne: 'परिणाम' },
  { en: 'Retain', ne: 'कायम राख्नु' },
  { en: 'Return', ne: 'फर्कनु' },
  { en: 'Reveal', ne: 'देखाउनु' },
  { en: 'Review', ne: 'समीक्षा गर्नु' },
  { en: 'Revise', ne: 'संशोधन गर्नु' },
  { en: 'Reward', ne: 'पुरस्कार' },
  { en: 'Risk', ne: 'जोखिम' },
  { en: 'Rotate', ne: 'घुमाउनु' },
  { en: 'Save', ne: 'बचाउनु' },
  { en: 'Search', ne: 'खोज्नु' },
  { en: 'Select', ne: 'छनोट गर्नु' },
  { en: 'Send', ne: 'पठाउनु' },
  { en: 'Separate', ne: 'अलग गर्नु' },
  { en: 'Serve', ne: 'सेवा गर्नु' },
  { en: 'Set', ne: 'सेट गर्नु' },
  { en: 'Share', ne: 'बाँड्नु' },
  { en: 'Show', ne: 'देखाउनु' },
  { en: 'Solve', ne: 'समाधान गर्नु' },
  { en: 'Sort', ne: 'वर्गीकरण गर्नु' },
  { en: 'Speak', ne: 'बोल्नु' },
  { en: 'Spend', ne: 'खर्च गर्नु' },
  { en: 'Spread', ne: 'फैलाउनु' },
  { en: 'Stand', ne: 'उभिनु' },
  { en: 'Start', ne: 'सुरु गर्नु' },
  { en: 'Stay', ne: 'बस्नु' },
  { en: 'Stop', ne: 'रोक्नु' },
  { en: 'Study', ne: 'अध्ययन गर्नु' },
  { en: 'Submit', ne: 'पेश गर्नु' },
  { en: 'Succeed', ne: 'सफल हुनु' },
  { en: 'Suggest', ne: 'सुझाव दिनु' },
  { en: 'Support', ne: 'समर्थन गर्नु' },
  { en: 'Suppose', ne: 'मान्नु' },
  { en: 'Surprise', ne: 'आश्चर्य' },
  { en: 'Survive', ne: 'बाँच्नु' },
  { en: 'Switch', ne: 'परिवर्तन गर्नु' },
  { en: 'Take', ne: 'लिनु' },
  { en: 'Talk', ne: 'कुरा गर्नु' },
  { en: 'Teach', ne: 'सिकाउनु' },
  { en: 'Tell', ne: 'भन्नु' },
  { en: 'Test', ne: 'परीक्षण गर्नु' },
  { en: 'Think', ne: 'सोच्नु' },
  { en: 'Throw', ne: 'फ्याँक्नु' },
  { en: 'Touch', ne: 'छोउनु' },
  { en: 'Train', ne: 'तालिम दिनु' },
  { en: 'Travel', ne: 'यात्रा गर्नु' },
  { en: 'Try', ne: 'प्रयास गर्नु' },
  { en: 'Turn', ne: 'घुमाउनु' },
  { en: 'Understand', ne: 'बुझ्नु' },
  { en: 'Update', ne: 'अद्यावधिक गर्नु' },
  { en: 'Use', ne: 'प्रयोग गर्नु' },
  { en: 'Validate', ne: 'प्रमाणित गर्नु' },
  { en: 'Vary', ne: 'फरक हुनु' },
  { en: 'Verify', ne: 'पुष्टि गर्नु' },
  { en: 'View', ne: 'हेर्नु' },
  { en: 'Visit', ne: 'भ्रमण गर्नु' },
  { en: 'Wait', ne: 'कुर्नु' },
  { en: 'Walk', ne: 'हिँड्नु' },
  { en: 'Want', ne: 'चाहनु' },
  { en: 'Warn', ne: 'चेतावनी दिनु' },
  { en: 'Watch', ne: 'हेर्नु' },
  { en: 'Wear', ne: 'लगाउनु' },
  { en: 'Win', ne: 'जित्नु' },
  { en: 'Withdraw', ne: 'फिर्ता लिनु' },
  { en: 'Work', ne: 'काम गर्नु' },
  { en: 'Worry', ne: 'चिन्ता गर्नु' },
  { en: 'Write', ne: 'लेख्नु' },
  { en: 'Yield', ne: 'उत्पादन दिनु' },
  { en: 'Zoom', ne: 'नजिक ल्याउनु' },
  { en: 'Transform', ne: 'रूपान्तरण गर्नु' },
  { en: 'Translate', ne: 'अनुवाद गर्नु' },
  { en: 'Transport', ne: 'यातायात गर्नु' },
  { en: 'Upgrade', ne: 'सुधार गर्नु' },
  { en: 'Utilize', ne: 'उपयोग गर्नु' },
  { en: 'Visualize', ne: 'कल्पना गर्नु' },
  { en: 'Volunteer', ne: 'स्वयंसेवा गर्नु' },
];
